.github/workflows/check-commits.yml
Add github workflow to ensure conventional commit format is being used.
=> chore: add conventional commits check

.github/workflows/build.yml, .tool-versions, dev-client/android/app/src/main/AndroidManifest.xml, dev-client/package.json
Adds CI workflow that verifies Android and iOS projects build. Still need to add iOS build to PR.
Progresses #23
=> chore: add workflow to build Android on push/PR

.github/workflows/build.yml
Adds an iOS build CI workflow.
Closes #23
=> chore: add iOS build workflow

dev-client/App.tsx, dev-client/components/Login.tsx, dev-client/package-lock.json, dev-client/package.json, dev-client/theme.ts
This button is just an experiment to learn how to create components, install nativebase and customize the theme. The next steps will be to update this button so it actually returns logs the user in.
I've temporarily commented out the map view. As part of this feature, I'd like to work out how to figure out navigation, so the user is redirected to the map view after being logged in.
Making this a separate PR to check out the following things:
- Does the theme setup look reasonable?
- folder structure for components
Related to #44
=> feat: Create beautiful but functionless login button

dev-client/components/common/IconLink.tsx, dev-client/components/common/RadioBlock.tsx, dev-client/components/projects/ProjectInputTab.tsx, dev-client/components/projects/ProjectSettingsTab.tsx, dev-client/components/projects/ProjectTabs.tsx, dev-client/components/projects/ProjectTeamTab.tsx, dev-client/components/projects/constants.ts, dev-client/translations/en.json, dev-client/types.ts
=> feat: Add Project Setting tab

dev-client/components/AppBar.tsx, dev-client/components/common/AddButton.tsx, dev-client/components/common/BottomNavigation.tsx, dev-client/components/common/MaterialIconButton.tsx, dev-client/components/common/ProgressCircle.tsx, dev-client/components/common/SearchBar.tsx, dev-client/components/projects/ProjectSitesTab.tsx, dev-client/components/projects/ProjectTabs.tsx, dev-client/components/projects/ProjectsEmptyView.tsx, dev-client/components/projects/ProjectsSearchView.tsx, dev-client/components/projects/constants.ts, dev-client/translations/en.json
Adds the projects site list.
Again, this is quite rough. The styling will need to be refined later. I'm trying to start splitting off features that are being reused into separate components.
Fixes #79
=> feat: project site view

dev-client/Gemfile, dev-client/Gemfile.lock
=> chore: update Cocoapods version

dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS.xcodeproj/xcshareddata/xcschemes/Terraso LandPKS.xcscheme, dev-client/ios/Terraso LandPKS/Info.plist
Fixes to:
* display name
* app category
* build configuration
* device orientation
* NSExceptionDomains
=> chore: additional build settings cleanup

.github/workflows/build.yml
build android on ubuntu; add gradle cache
=> chore: build android on ubuntu; add gradle cache

.github/workflows/build.yml, dev-client/.gitignore, dev-client/android/gradle.properties, dev-client/android/settings.gradle
* cache gradle locally
* adjust path for GitHub actions gradle cache
=> chore: more gradle caching

dev-client/src/types/index.ts, dev-client/src/types/projects.types.ts, dev-client/src/types/sites.types.ts, dev-client/src/types/users.types.ts
type reorganization suggestion
I have seen this pattern in other projects I believe it is better to keep code organized.
=> chore: re-organize types

dev-client/package-lock.json, dev-client/package.json, dev-client/src/components/map/SiteMap.tsx, dev-client/src/screens/SiteMapScreen.tsx
Long pressing the map will create a new pin.
Fixes #20 
Long pressing the map should create a new pin.
=> feat: long pressing the map will drop a new pin

dev-client/package.json
Adds `npm run format` to lint and fix.
=> chore: add format command

dev-client/package-lock.json, dev-client/package.json, dev-client/src/App.tsx
Got an error trying to make a site on the map, so I followed the instructions displayed in the error and it fixed it.
=> fix: Install library needed for uuid library

.github/dependabot.yml
Update dependabot.yml paths for npm and bundler.
=> chore: Update dependabot.yml paths

.github/workflows/ios_build.yml, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
Nump iOS build number before building and submitting
=> chore: bump iOS build number before building and submitting

.github/workflows/android_build.yml, .github/workflows/build.yml, .github/workflows/check-commits.yml, .github/workflows/ios_build.yml, .github/workflows/lint.yml
Add a step to build iOS and Android without signing or uploading.
=> chore: add build step (without sign/upload)

dev-client/package-lock.json, dev-client/package.json
=> chore: update prettier

.github/workflows/ios_build.yml, README.md, dev-client/.env.sample, dev-client/src/config/index.ts
Adds info for setting up mobile env
=> chore: Add env setup instructions to README

dev-client/.prettierrc
Fixes the format of the .prettierrc file.
=> fix: .prettierrc JSON format

README.md, dev-client/babel.config.js, dev-client/ios/Podfile.lock, dev-client/package-lock.json, dev-client/package.json, dev-client/src/App.tsx, dev-client/src/auth/index.ts, dev-client/src/components/common/BottomNavigation.tsx, dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/sites/CreateSiteView.tsx, dev-client/src/screens/AppScaffold.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/screens/constants.ts, dev-client/src/screens/index.ts, dev-client/src/translations/en.json
Adds a bottom sheet to the home screen.
Closes #50 
Closes #52
Sites should be visible in the bottom sheet. Clicking "show on map" should pan the map to the site. There is no location dashboard yet so clicking the site does nothing. Also updates the site map to not persist temporary sites, so there is at most one active at a time.
=> feat: home screen bottom sheet

dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/sites/CreateSiteView.tsx, dev-client/src/screens/CreateSiteScreen.tsx, dev-client/src/screens/constants.ts, dev-client/src/translations/en.json
Pins on the home screen now (roughly) match the design & you can create a new site from them. This is ready for review, it is just in draft as a reminder to change the base branch to main before merging, since this PR is stacked on the changes in #188 
Closes #31
=> feat: create site from pin on home screen

.github/workflows/android_build.yml, .github/workflows/build.yml, .github/workflows/ios_build.yml, .github/workflows/lint.yml
Add name to actions/setup-node workflow steps.
=> chore: add name to actions/setup-node workflow step

dev-client/ios/Podfile.lock, dev-client/ios/Terraso LandPKS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, dev-client/ios/Terraso LandPKS.xcworkspace/xcshareddata/swiftpm/Package.resolved, dev-client/ios/Terraso LandPKS/AppDelegate.h, dev-client/ios/Terraso LandPKS/AppDelegate.mm, dev-client/ios/Terraso LandPKS/Info.plist
fixed iOS auth code crash with exception `Thread 1: "<AppDelegate: 0x600003df21c0> does not conform to RNAppAuthAuthorizationFlowManager"`
=> fix: ios auth

.github/workflows/android_build.yml, .github/workflows/build.yml, .github/workflows/ios_build.yml
* clean up YAML for various build actions (fix capitalization, remove extra pipes)
* add workflow_dispatch to build
=> fix: clean up YAML for various build actions; add workflow_dispatch to build

.github/workflows/android_build.yml, .github/workflows/build.yml, .github/workflows/ios_build.yml, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
Improve mobile build actions
* use GitHub action for commits
* use MAPBOX_DOWNLOADS_TOKEN directly
=> fix: improve mobile build actions

dev-client/ios/Podfile.lock, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> build: bump iOS version number

dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/sites/SiteCard.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
A bunch of styling fixes for the home screen. Most notably, makes the site cards not look terrible.
=> feat: home screen styling fixes

dev-client/src/translations/en.json
Fixes https://github.com/techmatters/terraso-product/issues/343
=> fix: usda soil survey option label

dev-client/src/screens/ScreenScaffold.tsx, dev-client/src/translations/en.json
Fixes the label for the home screen in the bottom navigation button.
Progresses #223
=> fix: change home button label from "Map" to "Home"

dev-client/src/components/common/Accordion.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/sites/LocationDashboardScreen.tsx, dev-client/src/screens/SiteTransferProject.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
=> feat: update location dashboard style, enable for non-sites

dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/screens/HomeScreen.tsx
- Adds some padding to the bottom of the site list when it goes all the way to the bottom of the screen.
- Bottom sheet now displays over top of the search bar when fully open.
- Removed annoying scale bar behind search bar.
=> fix: minor polish round 1

.github/workflows/android_build.yml, dev-client/android/app/build.gradle
Bumps the patch version of the android version name when a new release is created so users can see that an update happened.
=> feat: bump patch version on android release

dev-client/src/components/common/Accordion.tsx, dev-client/src/components/common/Card.tsx, dev-client/src/components/common/Map.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/sites/LocationDashboardScreen.tsx, dev-client/src/components/sites/SiteCard.tsx, dev-client/src/components/sites/SiteSettingsScreen.tsx, dev-client/src/theme.ts
- location dashboard details accordion is now open by default
- location dashboard aerial view is now static rather than interactive
- home screen location popovers and site cards better match design ("close" icon and spacing)
- site cards now display an aerial view instead of photo icon
=> feat: minor polish round 2

.github/workflows/android_build.yml, .github/workflows/build-shared-android.yml, .github/workflows/build-shared-ios.yml, .github/workflows/build.yml, .github/workflows/ios_build.yml, dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
Refactor build workflows into reusable components. Avoids duplicate of steps in build and build+release workflows.
=> refactor: refactor build workflows into reusable components

dev-client/src/components/common/Map.tsx, dev-client/src/components/home/MapSearch.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/model/map/mapSlice.ts, dev-client/src/screens/HomeScreen.tsx
**NOTE: THIS PR IS BASED ON https://github.com/techmatters/terraso-mobile-client/pull/290 TO AVOID MERGE CONFLICTS. MAKE SURE THAT PR GETS MERGED AND BASE BRANCH IS UPDATED TO MAIN BEFORE MERGING THIS PR.**
Fixes #306 
Clicking on map button on site cards should open site callout as well as panning map to site.
=> feat: open callout when pressing site card's map button

dev-client/package-lock.json, dev-client/package.json
=> fix: Update project date format

dev-client/ios/Podfile.lock, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/src/components/home/SiteMap.tsx
Make map pin icons sizes more similar to each other on iOS and Android.
Fixes (once QA'd) #316.
=> fix: make map pin icons sizes closer on iOS and Android

dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/src/components/common/Map.tsx
Remove animation from site popover thumbnails
Fixes iOS portion of #317.
=> fix: Remove animation from site popover thumbnails

dev-client/ios/Podfile, dev-client/ios/Podfile.lock
Update MapboxMaps to 10.15.0, which is compatible with rnmapbox/maps 10.0.12.
=> fix: update MapboxMaps to 10.15.0

.github/workflows/build-shared-android.yml, dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
Bump iOS and Android versions to 30; fix Android bump method.
=> chore: bump version to 30

dev-client/android/app/proguard-rules.pro
=> fix: Change default proguard exception name to our package

dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/projects/ProjectTabs.tsx, dev-client/src/components/sites/CreateSiteView.tsx, dev-client/src/components/sites/LocationDashboardScreen.tsx, dev-client/src/components/sites/SiteCard.tsx, dev-client/src/components/sites/SiteSettingsScreen.tsx, dev-client/src/translations/en.json
Clean up localized text.
* don't use all-caps in strings file
* add site creation strings
* use constants for temporary text
Fixes #341.
=> fix: clean up localized text

dev-client/src/components/projects/CreateProjectView/Form.tsx, dev-client/src/components/projects/CreateProjectView/index.tsx, dev-client/src/components/projects/ProjectSettingsTab.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
Fixes some style issues on the project form
Fixes (once QA'd) #308. Also resolves one item in #310 
Project form on both project creation and edit views should have FAB in the correct location and elevation, and should always display a min length error message instead of a field required error message even when the name input is empty.
=> fix: project form style issues

dev-client/src/components/common/Card.tsx, dev-client/src/components/projects/ProjectListView/index.tsx, dev-client/src/components/projects/ProjectPreviewCard.tsx, dev-client/src/components/sites/SiteCard.tsx, dev-client/src/theme.ts
Updates project card to match spec.
Fixes (once QA'd) #309
Project cards should now look like design. Tapping anywhere on the card should navigate to the project's screen.
=> fix: bring project card in alignment with design

.github/ISSUE_TEMPLATE/mobile_bug_report.yml
Add mobile app bug report template
=> chore: add mobile app bug report template

dev-client/package-lock.json, dev-client/package.json
=> chore: bump client shared

dev-client/src/components/common/UserList.tsx, dev-client/src/components/common/search/SearchBar.tsx, dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/home/MapSearch.tsx, dev-client/src/components/home/SiteMap.tsx, dev-client/src/components/projects/ProjectSettingsTab.tsx, dev-client/src/components/projects/ProjectSitesTab.tsx, dev-client/src/components/sites/LocationDashboardScreen.tsx, dev-client/src/components/sites/SiteCard.tsx, dev-client/src/components/sites/SiteSettingsScreen.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/screens/LoginScreen.tsx, dev-client/src/screens/ProjectListScreen.tsx
Standardizes our use of style props to always use the abbreviated form.
=> chore: standardize to use abbreviated style props

dev-client/ios/Podfile.lock
=> build(deps): Update Podfile etc.

dev-client/package-lock.json, dev-client/package.json, dev-client/src/components/common/UserList.tsx, dev-client/src/components/projects/ProjectPreviewCard.tsx, dev-client/src/components/projects/ProjectTabs.tsx, dev-client/src/components/projects/ProjectTeamTab.tsx, dev-client/src/components/projects/constants.ts, dev-client/src/screens/SiteTransferProject.tsx
Updates existing screens to use ProjectMemberships instead of Group related Memberships.
Should be merged after [client-shared PR](https://github.com/techmatters/terraso-client-shared/pull/104)
Fixes #....
=> feat: Update screens to use ProjectMembership

dev-client/src/components/common/Form.tsx, dev-client/src/components/common/Map.tsx, dev-client/src/components/sites/CreateSiteView.tsx, dev-client/src/components/sites/validation.ts, dev-client/src/constants.ts, dev-client/src/model/map/mapSlice.ts, dev-client/src/screens/AppScaffold.tsx, dev-client/src/screens/CreateSiteScreen.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
@david-code this isn't ready to merge yet! Couple more bugs and I need to add tooltips, but I got frustrated with how Formik, yup, and NativeBase were all fighting with each other so I wrapped them all in our own form components and wanted to make the code available for review. The new components are in `Form.tsx`, and `CreateSiteView.tsx` has example usages. They have utility props for the happy path but are also component-ized for more complicated use cases. Figuring out how to get yup to validate the lat/lon string was nightmarish and still doesn't work :sob:
update: ready to merge! it seems that the form is a bit laggy for no reason other than that nativebase is slow :/ https://github.com/GeekyAnts/NativeBase/issues/4302
Fixes #197
Fixes #392 
Fixes #310 
Fixes #329
=> feat: create site form updates

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> chore: bump build number to 42

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> chore: bump build number to 43

.tool-versions
=> chore: bump node version to 18.18.0

dev-client/.eslintrc.js, dev-client/index.js, dev-client/src/components/common/Map.tsx, dev-client/src/components/common/Modal.tsx, dev-client/src/components/common/SpeedDial.tsx, dev-client/src/components/dataInputs/AddIntervalModal.tsx, dev-client/src/components/dataInputs/EditIntervalModal.tsx, dev-client/src/components/dataInputs/IntervalForm.tsx, dev-client/src/components/dataInputs/SoilScreen.tsx, dev-client/src/components/projects/CreateProjectView/Form.tsx, dev-client/src/components/projects/ProjectSettingsTab.tsx, dev-client/src/components/projects/ProjectTabs.tsx, dev-client/src/components/sites/LocationDashboardView.tsx, dev-client/src/components/sites/validation.ts, dev-client/src/types/index.ts
Use absolute paths for remaining imports
=> fix: use absolute paths for remaining imports

dev-client/src/components/common/UserList.tsx, dev-client/src/components/projects/AddUserToProjectScreen/MembershipControlList.tsx, dev-client/src/util.ts
* simplify the formatNames function
* rename it to formatName
* use in UserList
=> fix: simplify formatNames function and use in UserList

.tool-versions
=> chore: bump node to 20.9.0

dev-client/src/components/projects/ProjectSitesTab.tsx, dev-client/src/screens/SiteTransferProjectScreen.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
A few styling fixups for the Project Transfer Screen / Project Sites Tab, applying the latest styling changes. Also should fix the way the list is rendering.
=> fix: Fix up list rendering, styling for Site Transfer

dev-client/.depcheckrc, dev-client/android/app/build.gradle, dev-client/android/app/src/main/AndroidManifest.xml, dev-client/android/build.gradle, dev-client/android/gradle.properties, dev-client/ios/Terraso LandPKS/AppDelegate.h, dev-client/ios/Terraso LandPKS/Info.plist, dev-client/package-lock.json, dev-client/package.json, dev-client/src/auth/index.ts, dev-client/src/config/index.ts, dev-client/src/screens/LoginScreen.tsx, dev-client/src/translations/en.json
Add Microsoft login support.
Fixes https://github.com/techmatters/terraso-product/issues/436
Backend https://github.com/techmatters/terraso-backend/pull/940
=> feat: Add Microsoft and Apple login support

dev-client/package-lock.json, dev-client/package.json, dev-client/src/config/index.ts, dev-client/src/screens/LoginScreen.tsx, dev-client/src/screens/ScreenScaffold.tsx, dev-client/src/translations/en.json
Adds a "sign out button" to the app. Temporarily in the main navigation. Will eventually move to the settings page.
https://github.com/techmatters/terraso-mobile-client/issues/358
=> feat: Add sign out button to mobile app

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> chore: bump build to 51

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> chore: bump build to 52

dev-client/src/components/projects/ProjectSettingsTab.tsx
Remove archive project button on project settings screen.
Fixes #597.
=> fix: hide archive project button

dev-client/src/components/sites/SiteSettingsScreen.tsx, dev-client/src/translations/en.json
- remove pencil icon from input field
- update site list title
Fixes #488 and part of #490.
=> fix: remove pencil icon from input; update site list

dev-client/src/components/common/Form.tsx, dev-client/src/components/projects/CreateProjectView/Form.tsx, dev-client/src/components/projects/ProjectSettingsTab.tsx, dev-client/src/components/projects/ProjectTabs.tsx, dev-client/src/translations/en.json
- update the create project form
- update the tab order of the project screen
- update the project settings tab
Fixes #489.
=> fix: update project management screens to match designs

dev-client/src/components/common/Icons.tsx, dev-client/src/components/home/BottomSheet.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/translations/en.json
Update info sheet and empty sites sheet to match new designs
Fixes #490.
=> fix: update info sheet and empty sites sheet to match new designs

dev-client/package.json, dev-client/src/components/home/BottomSheet.tsx, dev-client/src/components/sites/CreateSiteView.tsx, dev-client/src/components/sites/SiteSettingsScreen.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/screens/LoginScreen.tsx, dev-client/src/screens/ScreenScaffold.tsx, dev-client/src/translations/en.json
Update site creation screen for new design.
Navigate home after site creation.
Fixes #491.
=> fix: update site creation screen

dev-client/package-lock.json, dev-client/package.json, dev-client/src/components/home/MapSearch.tsx, dev-client/src/util.ts
Adds coordinates check to home screen map search.
Fixes #370
Enter valid coordinates in the map search field and press enter on the keyboard. A temporary location popover should open at the correct coordinates.
=> feat: enter lat/long coordinates in map search

dev-client/__tests__/components/common/ListFilter.test.tsx, dev-client/package-lock.json, dev-client/package.json, dev-client/src/components/common/search/search.hooks.ts, dev-client/src/components/projects/ProjectSitesTab.tsx, dev-client/src/screens/HomeScreen.tsx, dev-client/src/screens/ProjectListScreen.tsx, dev-client/src/util.ts
=> chore: Import normalizeText function from client shared

dev-client/src/components/home/BottomSheet.tsx
For better readability of the function we have created, we decided to export the minimum and maximum values to variables for easier understanding and maintainability.
SafeAreaView bottom inset
Check the bottom insets, should work as before
=> chore: exported minimum and maximum values into variables

dev-client/src/components/common/Form.tsx, dev-client/src/components/sites/CreateSiteView.tsx
When showing location accuracy, show 5 decimal places.
=> fix: use 5 decimal places for GPS accuracy

Makefile, README.md, scripts/commit-msg.sample, scripts/pre-commit.sample
Add git hooks to lint on commit. Match what is done on backend.
=> chore: add git hooks to lint on commit

dev-client/src/components/sites/LocationDashboardView.tsx
Lowercase privacy label key on projects screen. Ensures label appears.
Fixes #663.
=> fix: lowercase privacy label key on projects screen

dev-client/src/screens/ProjectListScreen/components/ProjectPreviewCard.tsx, dev-client/src/translations/en.json
Format last modified dates on project preview cards.
Fixes #664.
=> fix: format last modified dates on project preview cards

.github/workflows/build-shared-ios.yml, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
env file needs to be at project root.
=> fix: Fix iOS Build

dev-client/ios/Podfile, dev-client/ios/Podfile.lock
IUpdate CocoaPods dependencies
Bump MapboxMpas to 10.16.3. Auto-update others.
=> chore: update CocoaPods dependencies

.github/dependabot.yml
Have dependabot update dependencies for all fixes, not just security fixes.
=> chore: update dependencies for all fixes, not just security fixes

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist
=> chore: bump build to 73

dev-client/android/app/build.gradle, dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj, dev-client/ios/Terraso LandPKS/Info.plist, dev-client/src/screens/SlopeScreen/SlopeMeterScreen.tsx
* restore camera view on slope meter screen
* bump build number to 74
=> fix: restore camera view on slope meter screen

dev-client/src/context/BottomSheetPrivacyModalContext.tsx, dev-client/src/hooks/useInfoPress.tsx
Add copyright notices to more files.
=> docs: add copyright notices

dev-client/src/translations/en.json
Update title of Sites List
One fix for #752
=> fix: update title for Sites List

dev-client/package-lock.json, dev-client/package.json, dev-client/src/screens/SoilScreen/components/EditIntervalModalContent.tsx, dev-client/src/screens/SoilScreen/components/SoilDepthIntervalSummary.tsx
Activate default soil input default methods. Rework of #827.
=> feat: Activate default soil input default methods

dev-client/package.json
=> fix: expo-font

dev-client/android/app/build.gradle, dev-client/ios/TerrasoLandPKS.xcodeproj/project.pbxproj, dev-client/ios/TerrasoLandPKS/Info.plist
Add NSMotionUsageDescription. Hopefully fixes crash on quit on iOS.
=> fix: Add NSMotionUsageDescription

dev-client/package-lock.json, dev-client/package.json, dev-client/src/screens/SlopeScreen/SlopeScreen.tsx, dev-client/src/screens/SlopeScreen/SlopeShapeScreen.tsx, dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx, dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx, dev-client/src/screens/SoilScreen/components/EditIntervalModalContent.tsx, dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
Fixes the crash when viewing a site that has just been created.
Fixes https://github.com/techmatters/terraso-mobile-client/issues/845
Needs  https://github.com/techmatters/terraso-client-shared/pull/291
User should be able to create a new site, and then view that site.
=> fix: crash on viewing new site

dev-client/android/app/build.gradle, dev-client/ios/TerrasoLandPKS.xcodeproj/project.pbxproj, dev-client/ios/TerrasoLandPKS/Info.plist, dev-client/src/components/ListFilter.tsx
Fixes the text handling in the list search component.
Attempted fix for https://github.com/techmatters/terraso-mobile-client/issues/852
=> fix: don't ignore every other letter input into list search component

dev-client/android/app/build.gradle, dev-client/ios/TerrasoLandPKS.xcodeproj/project.pbxproj, dev-client/ios/TerrasoLandPKS/Info.plist, dev-client/src/components/ListFilter.tsx, dev-client/src/components/StaticMapView.tsx, dev-client/src/screens/HomeScreen/HomeScreen.tsx
Hopefully fixes the issue where the map occasionally doesn't properly zoom into the user's location on initial load.
Tries to fix https://github.com/techmatters/terraso-mobile-client/issues/867
=> fix: properly show locations on initial map load

dev-client/package-lock.json, dev-client/package.json
Bump @sentry/react-native to 5.19.1.
=> chore: bump @sentry/react-native to 5.19.1

dev-client/ios/Podfile, dev-client/ios/Podfile.lock, dev-client/package-lock.json, dev-client/package.json
Update MapboxMaps pod to 10.16.15; update @rnmapbox/maps to 10.1.15.
=> chore: update MapboxMaps to 10.16.15; update @rnmapbox/maps to 10.1.15

dev-client/src/screens/ProjectInputScreen/DepthIntervalTable.tsx, dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
Correctly render soil depth pit intervals.
Also fixes warning about empty dimension.
Fixes #890.
- Open or create project
- Expand the Soil Pit section
=> fix: correctly render soil depth pit intervals

dev-client/ios/Podfile
Clean up Podfile with Rubocop.
=> style: clean up Podfile with Rubocop

README.md, scripts/commit-msg.sample
Update ruby and android instructions in readme
Also updated commit message git hook to use python3
=> docs: Update ruby and android instructions in readme

dev-client/src/components/IntervalForm.tsx, dev-client/src/screens/SoilScreen/components/EditIntervalModalContent.tsx, dev-client/src/screens/SoilScreen/components/SoilDepthIntervalSummary.tsx, dev-client/src/screens/SoilScreen/components/SoilPitInputScreenScaffold.tsx, dev-client/src/screens/SoilScreen/utils/renderValues.ts, dev-client/src/translations/en.json
• Use i18n strings for renderDepthInterval
• Use en dashes for depth intervals
• Use standard language for camera/photo library picker
=> fix: improve depth interval and camera / photo library strings

.github/workflows/build-shared-android.yml
Reverts techmatters/terraso-mobile-client#960
=> Revert "chore: use filippoLeporati93/android-release-signer action"

dev-client/package-lock.json, dev-client/package.json, dev-client/src/constants.ts, dev-client/src/screens/CreateProjectScreen/components/Form.tsx, dev-client/src/screens/ProjectSettingsScreen.tsx, dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx, dev-client/src/translations/en.json
Fixes the bugs I introduced to the project settings screen in #959 
#977 
https://github.com/techmatters/terraso-backend/issues/1212
Project manager should be able to update project name, measurement units should display properly.
=> fix: project settings screen bugs

dev-client/package-lock.json, dev-client/package.json
=> build: update munsell to 1.1.5

dev-client/package-lock.json, dev-client/package.json
=> build: update yup to 1.4.0

dev-client/package-lock.json, dev-client/package.json
Update expo, expo-camera and expo-crypto.
=> chore: update expo, expo-camera and expo-crypto

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.8.1.
=> build: update react-native-reanimated to 3.8.1

dev-client/package-lock.json, dev-client/package.json
update react-native-screens to 3.30.1.
=> build: update react-native-screens to 3.30.1

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.10.1

dev-client/package-lock.json, dev-client/package.json
update react-native-pager-view to 6.3.0.
=> build: update react-native-pager-view to 6.3.0

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.1.0.
=> build: update react-native-svg to 15.1.0

dev-client/package-lock.json, dev-client/package.json
=> build: update ts-morph to 22.0.0

dev-client/package-lock.json, dev-client/package.json
update @types/react to 18.2.73.
=> build: update @types/react to 18.2.73

dev-client/package-lock.json, dev-client/package.json
update react-native-get-random-values to 1.11.0.
=> build: update react-native-get-random-values to 1.11.0

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 5.20.0.
=> build: update @sentry/react-native to 5.20.0

dev-client/package-lock.json, dev-client/package.json
Update:
- @babel/core@7.24.3
- @babel/preset-env@7.24.3
- @babel/preset-typescript@7.24.1
- @babel/runtime@7.24.1
=> build: update @babel/runtime @babel/preset-typescript @babel/preset-env  @babel/core

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native to 12.4.5.
=> build: update @testing-library/react-native to 12.4.5

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.19.
=> build: update @rnmapbox/maps to 10.1.19

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.11.0

dev-client/package-lock.json, dev-client/package.json
=> fix: update i18next to 23.11.1

dev-client/package-lock.json, dev-client/package.json
=> build: update typescript to 5.4.5

README.md
better docs
they make the docs better
=> docs: better docs on running the app locally

dev-client/package-lock.json, dev-client/package.json
=> chore: update i18next to 23.11.2

dev-client/src/screens/SoilScreen/SoilScreen.tsx, dev-client/src/screens/SoilScreen/components/SoilSurfaceStatus.tsx
Quick fix for a bug courtney noticed which was barely more effort to just fix now as it'd be to write a proper bug report.
=> fix: surface cracking data input summary

dev-client/package-lock.json, dev-client/package.json
Update react-devtools to 5.1.0.
=> chore: update react-devtools to 5.1.0

dev-client/package-lock.json, dev-client/package.json
update @types/react to 18.2.79.
=> build: update @types/react to 18.2.79

dev-client/src/screens/SoilScreen/components/SoilSurfaceStatus.tsx
Checks if the vertical cracking value exists before trying to render it.
=> fix: surface status empty value

dev-client/package-lock.json, dev-client/package.json
update react-i18next to 14.1.1.
=> chore: update react-i18next to 14.1.1

dev-client/package-lock.json, dev-client/package.json
Update @react-native-community/cli-doctor to 13.6.5.
=> chore: update @react-native-community/cli-doctor to 13.6.5

dev-client/src/navigation/components/AppBar.tsx, dev-client/src/screens/HomeScreen/HomeScreen.tsx, dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
Remove hamburger menu.
Fixes #1164.
=> fix: hide hamburger menu

dev-client/app.config.ts
Remove NSMicrophoneUsageDescription from app.config.ts.
Fixes #1171.
=> fix: remove NSMicrophoneUsageDescription from app.config.ts

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.21.
=> build: update @rnmapbox/maps to 10.1.21

dev-client/package-lock.json, dev-client/package.json
=> fix: update formik to 2.4.6

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.11.3

dev-client/package-lock.json, dev-client/package.json
update @babel/runtime @babel/preset-env @babel/core to 7.24.5.
=> build: update @babel/runtime @babel/preset-env @babel/core to 7.24.5

dev-client/package-lock.json, dev-client/package.json
update @expo/vector-icons to 14.0.1.
=> build: update @expo/vector-icons to 14.0.1

dev-client/package-lock.json, dev-client/package.json
Update @testing-library/react-native to 12.5.0.
=> build: update @testing-library/react-native to 12.5.0

dev-client/package-lock.json, dev-client/package.json
update react-native-pager-view to 6.3.1.
=> build: update react-native-pager-view to 6.3.1

dev-client/package-lock.json, dev-client/package.json
update react-native-screens to 3.31.1.
=> build: update react-native-screens to 3.31.1

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler to 2.16.1.
=> build: update react-native-gesture-handler to 2.16.1

dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- remove transfer menu
- remove copy donwload link
- remove pencil icon
Addresses https://github.com/techmatters/terraso-product/issues/703
=> fix: update site settings screen

dev-client/src/screens/SiteScreen/SiteScreen.tsx
cCorrect font size (body1) and border radius (4px) in soil id box.
Partially addresses #543
=> fix: correct font size and border radius in soil id box

dev-client/src/components/buttons/ButtonList.tsx, dev-client/src/components/buttons/ListButton.tsx, dev-client/src/components/modals/ActionsModal.tsx, dev-client/src/components/modals/ConfirmModal.tsx, dev-client/src/components/modals/LogoutModal.tsx, dev-client/src/config/index.ts, dev-client/src/navigation/navigators/BottomNavigator.tsx, dev-client/src/navigation/screenDefinitions.tsx, dev-client/src/screens/BottomTabsScreen.tsx, dev-client/src/screens/SettingsScreen/SettingsScreen.tsx, dev-client/src/screens/SettingsScreen/components/UserIndicatorComponent.tsx, dev-client/src/screens/SettingsScreen/components/VersionIndicatorComponent.tsx, dev-client/src/screens/SettingsScreen/components/actions/DeleteAccountButton.tsx, dev-client/src/screens/SettingsScreen/components/actions/LogOutButton.tsx, dev-client/src/translations/en.json
Add the basic settings screen per design requirements. Introduce a new button type (ListButton) and container (ButtonList) to implement its controls, and add support for displaying application version. Refactor the existing logout system to use a common modal, now compliant with design spec, built on the existing ActionModal.
Note that the 'delete account' button is not currently hooked into functionality, as the 'delete' workflow is not yet implemented.
Fixes #1163
Open settings screen in bottom navbar. Verify expected functionality.
=> feat: settings screen initial implementation

dev-client/src/config/index.ts
remove no-op line (ENV_CONFIG.MICROSOFT_SIGNATURE_HASH) from config/index.ts
=> fix: remove extra line from config/index.ts

.github/workflows/android_build.yml, .github/workflows/build-shared-android.yml, .github/workflows/build-shared-ios.yml, .github/workflows/build.yml, .github/workflows/ios_build.yml
Use SENTRY_ENABLED var instead of secret. (This should be visible to developers.)
=> fix: use SENTRY_ENABLED var instead of secret

dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/LoginScreen-test.tsx.snap, dev-client/src/components/AddButton.tsx, dev-client/src/screens/HomeScreen/components/CalloutDetail.tsx, dev-client/src/screens/HomeScreen/components/TemporarySiteCallout.tsx, dev-client/src/screens/LoginScreen.tsx, dev-client/src/screens/ProjectListScreen/components/ProjectPreviewCard.tsx, dev-client/src/screens/ProjectSettingsScreen.tsx, dev-client/src/screens/SiteScreen/SiteScreen.tsx, dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
Consistently use textTransform to make text uppercase. Avoid using toUpperCase() in some places.
=> fix: consistently use textTransform to make text uppercase

dev-client/src/translations/en.json
Remove audit log from description text.
=> fix: remove audit log from description text

dev-client/package-lock.json, dev-client/package.json
Update @rnmapbox/maps to 10.1.23.
=> build: update @rnmapbox/maps to 10.1.23

dev-client/package-lock.json, dev-client/package.json
update react-devtools to 5.2.0.
=> build: update react-devtools to 5.2.0

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler to 2.16.2.
=> build: update react-native-gesture-handler to 2.16.2

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.11.0.
=> build: update react-native-reanimated to 3.11.0

dev-client/package-lock.json, dev-client/package.json
Update @sentry/react-native to 5.22.2.
=> build: update @sentry/react-native to 5.22.2

dev-client/src/screens/ColorAnalysisScreen/components/ColorCropScreen.tsx, dev-client/src/screens/SoilScreen/ColorScreen/utils/munsellConversions.ts, dev-client/src/screens/SoilScreen/ColorScreen/utils/soilColorValidation.ts
- small refactor to move some code around without changes
- uses a less strict threshold for color similarity
- fixes the bad argument to  
Related to https://github.com/techmatters/terraso-mobile-client/issues/1319 and maybe others?
=> fix: color algorithm fixes

dev-client/.eslintrc.js, dev-client/src/components/BulletList.tsx, dev-client/src/components/Card.tsx, dev-client/src/components/ScreenFormWrapper.tsx, dev-client/src/components/SiteNoteForm.tsx, dev-client/src/components/links/ExternalLink.tsx, dev-client/src/components/modals/privacy/PrivacyInfoContent.tsx, dev-client/src/screens/CreateProjectScreen/components/CreateProjectForm.tsx, dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx, dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx, dev-client/src/screens/HomeScreen/components/LandPKSInfo.tsx, dev-client/src/screens/LocationScreens/components/ProjectInstructionsButton.tsx, dev-client/src/screens/ManageTeamMemberScreen.tsx, dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx, dev-client/src/screens/ReadNoteScreen.tsx
Add react/jsx-curly-brace-presence rule to .eslintrc, run linter to enforce style.
We were previously inconsistent in our use.
=> fix: add react/jsx-curly-brace-presence rule to .eslintrc, run linter to enforce style

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.24.
=> build: update @rnmapbox/maps to 10.1.24

dev-client/package-lock.json, dev-client/package.json
update @expo/vector-icons to 14.0.2.
=> build: update @expo/vector-icons to 14.0.2

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.11.4

dev-client/package-lock.json, dev-client/package.json
update react-native-svg-transformer to 1.4.0
=> build: update react-native-svg-transformer to 1.4.0

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.3.0.
=> build: update react-native-svg to 15.3.0

dev-client/src/components/Card.tsx, dev-client/src/components/SiteCard.tsx
update site overlay card to match design
- remove last modified
- fix font size and spacing
Addresses #1275
=> fix: update site overlay card to match design

dev-client/app.config.ts
restore signingConfig removal, but only on GitHub CI.
=> fix: restore signingConfig removal, but only on GitHub CI

dev-client/src/screens/SlopeScreen/SlopeShapeScreen.tsx, dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx, dev-client/src/screens/SoilScreen/ColorScreen/ColorScreen.tsx, dev-client/src/screens/SoilScreen/TextureScreen.tsx, dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
remove last modified component from soil texture/rock fragment, color, slope shape, slope steepness, vertical cracking.
Addresses #1383 and/or #1385.
=> fix: remove last modified component

dev-client/__tests__/integration/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap, dev-client/src/components/DataInputSummary.tsx, dev-client/src/components/form/FormSwitch.tsx, dev-client/src/screens/SoilScreen/components/EditIntervalModal.tsx
improve layout on soil data entry screen
- shrink soil surface text to prevent label/value collision
- add spacing between switches and text
=> fix: improve layout on soil data entry screen

dev-client/__tests__/integration/__snapshots__/LoginScreen-test.tsx.snap, dev-client/app.config.ts, dev-client/package-lock.json, dev-client/package.json, dev-client/src/auth/index.ts, dev-client/src/config/index.ts, dev-client/src/screens/LoginScreen.tsx
Add Sign In With Apple (via authentication).
Addresses https://github.com/techmatters/terraso-product/issues/680
Depends on https://github.com/techmatters/terraso-backend/pull/1301
=> feat: Add Sign In With Apple

dev-client/src/components/buttons/DoneButton.tsx, dev-client/src/screens/SlopeScreen/SlopeShapeScreen.tsx, dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx, dev-client/src/screens/SoilScreen/ColorScreen/ColorScreen.tsx, dev-client/src/screens/SoilScreen/TextureScreen.tsx, dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
Add "Done" button to rock fragments screen.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/860
=> fix: add done button to rock fragments screen

dev-client/package-lock.json, dev-client/package.json
update @babel/core @babel/preset-env @babel/preset-typescript @babel/runtime to 7.24.6.
=> build: update @babel/core @babel/preset-env @babel/preset-typescript @babel/runtime to 7.24.6

dev-client/src/navigation/navigators/BottomNavigator.tsx
increase spacing between footer buttons
Addresses #769.
=> fix: increase spacing between footer buttons

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.12.0.
=> build: update react-native-reanimated to 3.12.0

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context to 4.10.3.
=> build: update react-native-safe-area-context to 4.10.3

dev-client/.depcheckrc, dev-client/package-lock.json, dev-client/package.json
Install expo-dev-client; start in development mode, not expo go.
=> chore: install expo-dev-client; start in development mode, not expo go

dev-client/package-lock.json, dev-client/package.json
Update react-native-safe-area-context to 4.10.4.
=> build: update react-native-safe-area-context to 4.10.4

dev-client/src/translations/en.json
Change 'log out' to 'sign out' in settings.
Part of https://github.com/techmatters/terraso-product/issues/850.
=> fix: change 'log out' to 'sign out'

dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/src/components/ProjectSelect.tsx, dev-client/src/components/inputs/Select.tsx, dev-client/src/translations/en.json
Make entire select box clickable on IOS.
Addresses #1313.
=> fix: make entire select box clickable

dev-client/package-lock.json, dev-client/package.json
update  @sentry/react-native to 5.23.0.
=> build: update  @sentry/react-native to 5.23.0

dev-client/package-lock.json, dev-client/package.json
update @babel/runtime @babel/preset-typescript  @babel/preset-env @babel/core to 7.24.7.
=> build: update @babel/runtime @babel/preset-typescript  @babel/preset-env @babel/core to 7.24.7

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/cli-doctor to 13.6.9.
=> build: update @react-native-community/cli-doctor to 13.6.9

dev-client/package-lock.json, dev-client/package.json
=> build: update prettier to 3.3.1

dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap, dev-client/src/screens/ProjectInputScreen/RequiredDataSettings.tsx, dev-client/src/translations/en.json
update labels and descriptions for data collection methods
Addresses #1493.
=> fix: update labels and descriptions for data collection methods

dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx, dev-client/src/screens/ProjectSettingsScreen.tsx, dev-client/src/translations/en.json
Remove measurement units from project settings
Addresses part of https://github.com/techmatters/terraso-mobile-client/issues/1488
=> fix: remove measurement units from project settings

dev-client/src/translations/en.json
Update project text.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1502
=> fix: update project text

dev-client/src/screens/CreateSiteScreen/CreateSiteScreen.tsx, dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx, dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx, dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx, dev-client/src/screens/LocationScreens/components/CreateSiteButton.tsx
Save elevation to database on site creation.
Addresses https://github.com/techmatters/terraso-product/issues/774
Depends on https://github.com/techmatters/terraso-mobile-client/pull/1315
=> fix: save elevation on site creation

dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/src/navigation/constants.ts, dev-client/src/navigation/navigators/ProjectTabNavigator.tsx, dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx, dev-client/src/screens/ProjectSettingsScreen.tsx, dev-client/src/screens/ProjectSitesScreen.tsx, dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
- set background colors for project tabs
- add gray background color to theme
- localize project tab labels
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1506
=> fix: set background colors for project tabs

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 5.24.0.
=> build: update @sentry/react-native to 5.24.0

dev-client/package-lock.json, dev-client/package.json
=> build: update prettier to 3.3.2

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.27
=> build: update @rnmapbox/maps to 10.1.27

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context to 4.10.5.
=> build: update react-native-safe-area-context to 4.10.5

dev-client/src/screens/ProjectSettingsScreen.tsx, dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
Update button icons to match spec.
Fixes #771.
=> fix: update button icons to match spec

dev-client/.depcheckrc, dev-client/src/App.tsx
Track console warnings and errors with Sentry.
=> fix: add console integration to Sentry

dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx, dev-client/src/translations/en.json
Add heading to site settings screen.
Addresses #1589.
=> fix: add heading to site settings screen

dev-client/src/hooks/useKeyboardStatus.ts, dev-client/src/screens/BottomTabsScreen.tsx
Hide bottom tabs when keyboard is shown
Addresses #1595.
=> fix: hide bottom tabs when keyboard is shown

dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx, dev-client/src/translations/en.json
Show confirmation dialog before transferring sites to another project.
Addresses #1598.
=> feat: show confirmation dialog before transferring sites to another project

dev-client/src/components/BadgedIcon.tsx, dev-client/src/theme.ts
Remove background colors for icon buttons.
=> fix: remove background colors for icon buttons

dev-client/src/components/AddDepthModal.tsx, dev-client/src/components/tables/DataGridTable.tsx, dev-client/src/screens/ProjectInputScreen/SoilPitSettings.tsx, dev-client/src/screens/SoilScreen/SoilScreen.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
update soil pit depth table to match design
- add spacing
- add dividers
- make header larger
Addresses #1591.
=> fix: update soil pit depth table to match design

dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx, dev-client/src/screens/LocationScreens/LocationDashboardScreen.tsx, dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx, dev-client/src/screens/ProjectSitesScreen.tsx, dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx, dev-client/src/screens/SlopeScreen/SlopeScreen.tsx
Set site screen background colors.
Also clean up project screen background color parameters to have consistent formatting.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1601
=> fix: set site screen background colors

dev-client/src/App.tsx, dev-client/src/components/buttons/list/ButtonList.tsx, dev-client/src/components/modals/Modal.tsx, dev-client/src/screens/HomeScreen/components/SiteClusterCalloutListItem.tsx, dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx, dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx, dev-client/src/screens/LocationScreens/components/soilInfo/SiteScoreInfoContent.tsx, dev-client/src/screens/LocationScreens/components/soilInfo/TempScoreInfoContent.tsx, dev-client/src/screens/ManageTeamMemberScreen.tsx, dev-client/src/screens/ProjectSitesScreen.tsx, dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx, dev-client/src/screens/ProjectTeamScreen/components/UserInfo.tsx, dev-client/src/screens/ProjectTeamScreen/components/UserItem.tsx, dev-client/src/screens/ProjectTeamScreen/components/UserList.tsx, dev-client/src/theme.ts, dev-client/src/translations/en.json
correct manage team screen
- add header
- fix spacing and dividers
Move dividers from NativeBase to React Native Paper.
=> fix: correct manage team screen; move dividers off of NativeBase

dev-client/src/screens/LocationScreens/components/soilId/SoilMatchTile.tsx
I'd forgotten to remove a TODO comment for myself. Remove it.
=> chore: Remove old TODO comment

.github/workflows/android_build.yml, .github/workflows/build-shared-android.yml, .github/workflows/build-shared-ios.yml, .github/workflows/ios_build.yml, dev-client/app.config.ts, dev-client/src/config/index.ts, dev-client/src/screens/UserSettingsScreen/components/VersionIndicatorComponent.tsx, dev-client/src/translations/en.json
- separate out build and version
- update IOS bundle ID
- update app name
=> fix: build and version cleanup

dev-client/app.config.ts
Add aps-environment entitlement to app config. 
Fixes ITMS-90078 push notification warning
=> fix: add aps-environment entitlement

.github/workflows/build-shared-ios.yml
Update Xcode from 15.2 to to 15.4.
=> build: update Xcode to 15.4

dev-client/src/App.tsx
Suppress suppress reanimated warning.
Fixes #1548.
=> fix: suppress reanimated warning

dev-client/src/components/StaticMapView.tsx
Remove unused coordsToString export.
=> fix: remove unused coordsToString export

dev-client/src/translations/en.json
Update project sites tab text from Figma.
Addresses #1127.
=> fix: update project sites tab text

dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/src/translations/en.json
Update strings with 'LandPKS Soil ID' where appropriate.
=> fix: update strings with 'LandPKS Soil ID' where appropriate

dev-client/package-lock.json, dev-client/package.json
=> build: update typescript to 5.5.3

dev-client/package-lock.json, dev-client/package.json
update @ianvs/prettier-plugin-sort-imports to 4.3.0.
=> build: update @ianvs/prettier-plugin-sort-imports to 4.3.0

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.13.0.
=> build: update react-native-reanimated to 3.13.0

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context to 4.10.7.
=> build: update react-native-safe-area-context to 4.10.7

dev-client/package-lock.json, dev-client/package.json
update @react-navigation/bottom-tabs to 6.6.0.
=> build: update @react-navigation/bottom-tabs to 6.6.0

dev-client/package-lock.json, dev-client/package.json
update react-devtools to 5.3.1.
=> build: update react-devtools to 5.3.1

dev-client/package-lock.json, dev-client/package.json
update uuid to 10.0.0 and update terraso-client-shared.
=> build: update uuid to 10.0.0 and update terraso-client-shared

dev-client/package-lock.json, dev-client/package.json
update react-native to 0.74.3.
=> build: update react-native to 0.74.3

dev-client/package-lock.json, dev-client/package.json
update expo-media-library to 16.0.4.
=> build: update expo-media-library to 16.0.4

dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
Remove button shadow and add accordion spacing to project transfer screen
Addresses #570 .
=> fix: remove button shadow and add accordion spacing from project transfer screen

dev-client/src/components/ListFilter.tsx, dev-client/src/screens/HomeScreen/components/MapSearch.tsx
Increase map search bar width.
This mitigates #1740 (but doesn't solve it entirely).
=> fix: increase map search bar width

dev-client/package-lock.json, dev-client/package.json
bump @sentry/react-native to 5.25.0.
=> build: bump @sentry/react-native to 5.25.0

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context to 4.10.8.
=> build: update react-native-safe-area-context to 4.10.8

dev-client/package-lock.json, dev-client/package.json
update react-native-svg-transformer to 1.5.0.
=> build: update react-native-svg-transformer to 1.5.0

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.14.0.
=> build: update react-native-reanimated to 3.14.0

dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/src/components/buttons/TextButton.tsx, dev-client/src/components/links/ExternalLink.tsx
Reimplement `ExternalLink` to be compliant with spec -- to assist with future work, this involved spinning off a common `TextButton` component which supports this component as well as expected future work in the components documentation.
#1289
Open sections of the application containing external links. Verify that they match the component specification. (Note that this is not the same as `InternalLink`, which will eventually open an embedded web view rather than a browser window.)
=> feat: spec compliance for ExternalLink

dev-client/package-lock.json, dev-client/package.json
update expo-dev-client to 4.0.20.
=> build: update expo-dev-client to 4.0.20

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.28.
=> build: update @rnmapbox/maps to 10.1.28

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/cli-doctor to 14.0.0.
=> build: update @react-native-community/cli-doctor to 14.0.0

dev-client/package-lock.json, dev-client/package.json
Update expo-camera to 15.0.14.
=> build: update expo-camera to 15.0.14

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 5.26.0.
=> build: update @sentry/react-native to 5.26.0

dev-client/package-lock.json, dev-client/package.json
update react-i18next to 15.0.0.
=> build: update react-i18next to 15.0.0

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.12.1

dev-client/package-lock.json, dev-client/package.json
update eslint-plugin-prettier to 5.2.1.
=> build: update eslint-plugin-prettier to 5.2.1

dev-client/package-lock.json, dev-client/package.json
update @ianvs/prettier-plugin-sort-imports to 4.3.1.
=> build: update @ianvs/prettier-plugin-sort-imports to 4.3.1

dev-client/src/screens/LoginScreen.tsx
Displays a loading indicator during login while waiting for backend response.
Resolves (once QA'd) #1223
=> feat: display loading indicator while waiting for login response

dev-client/package-lock.json, dev-client/package.json
update @babel/preset-env to 7.24.8
=> build: update @babel/preset-env to 7.24.8

dev-client/package-lock.json, dev-client/package.json
=> build: update typescript to 5.5.4

dev-client/package-lock.json, dev-client/package.json
update expo-apple-authentication to 6.4.2
=> build: update expo-apple-authentication to 6.4.2

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.12.2

dev-client/package-lock.json, dev-client/package.json
bump gorhom/bottom-sheet to 4.6.4
=> build: bump gorhom/bottom-sheet to 4.6.4

dev-client/package-lock.json, dev-client/package.json
=> build: update use-debounce to 10.0.2

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native to 12.5.2
=> build: update @testing-library/react-native to 12.5.2

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/LocationDashboardScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
bump @react-navigation/native-stack to 6.11.0
=> build: bump @react-navigation/native-stack to 6.11.0

dev-client/__tests__/snapshot/__snapshots__/LoginScreen-test.tsx.snap, dev-client/src/translations/en.json
Update tagline to "Discover your land's potential."
Addresses #925.
=> fix: update tagline

dev-client/package-lock.json, dev-client/package.json
bump @sentry/react-native to 5.28.0.
=> build: bump @sentry/react-native to 5.28.0

dev-client/package-lock.json, dev-client/package.json
bump expo-dev-client to 4.0.22.
=> build: bump expo-dev-client to 4.0.22

dev-client/package-lock.json, dev-client/package.json
update @babel/preset-env@7.25.3  @babel/runtime@7.25.0.
=> build: update @babel/preset-env@7.25.3  @babel/runtime@7.25.0

dev-client/package-lock.json, dev-client/package.json
=> build: bump react-i18next to 15.0.1

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native to 12.5.3.
=> build: update @testing-library/react-native to 12.5.3

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.15.0.
=> build: update react-native-reanimated to 3.15.0

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.5.0.
=> build: update react-native-svg to 15.5.0

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler to 2.18.1.
=> build: update react-native-gesture-handler to 2.18.1

dev-client/package-lock.json, dev-client/package.json
=> build: update ts-jest to 29.2.4

dev-client/package-lock.json, dev-client/package.json
update react-native-mmkv-storage to 0.10.2.
=> build: update react-native-mmkv-storage to 0.10.2

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 5.30.0
=> build: update @sentry/react-native to 5.30.0

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.14.0

dev-client/package-lock.json, dev-client/package.json
bump @testing-library/react-native to 12.6.0.
=> build: bump @testing-library/react-native to 12.6.0

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/cli-doctor to 14.0.1.
=> build: update @react-native-community/cli-doctor to 14.0.1

dev-client/metro.config.js, dev-client/package-lock.json, dev-client/package.json
Update expo to 51.0.28 + remove Sentry serializer.
=> build: update expo to 51.0.28 + remove Sentry serializer

dev-client/package-lock.json, dev-client/package.json
update  @rnmapbox/maps to 10.1.29
=> build: update  @rnmapbox/maps to 10.1.29

dev-client/package-lock.json, dev-client/package.json
=> build: bump @types/react to 18.3.4

dev-client/package-lock.json, dev-client/package.json
=> build: bump expo to ~51.0.30

dev-client/package-lock.json, dev-client/package.json
build: update expo-dev-client to 4.0.24.
=> build: update expo-dev-client to 4.0.24

dev-client/package-lock.json, dev-client/package.json
update react-native-mmkv-storage to 0.10.3.
=> build: update react-native-mmkv-storage to 0.10.3

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.6.0.
=> build: update react-native-svg to 15.6.0

dev-client/package-lock.json, dev-client/package.json
=> build: update jest-expo to 51.0.4

dev-client/package-lock.json, dev-client/package.json
update react-native-pager-view to 6.4.0
=> build: update react-native-pager-view to 6.4.0

dev-client/package-lock.json, dev-client/package.json
bump @babel/preset-env and @babel/runtime to 7.25.4.
=> build: bump @babel/preset-env  @babel/runtime to 7.25.4

dev-client/package-lock.json, dev-client/package.json
bump expo-dev-client to 4.0.25.
=> build: bump expo-dev-client to 4.0.25

.github/workflows/build-shared-android.yml
use .tool-versions for java version.
=> fix: use .tool-versions for java version

dev-client/package-lock.json, dev-client/package.json
bump @sentry/react-native to 5.31.1.
=> build: bump @sentry/react-native to 5.31.1

README.md
Add instructions on using specific iOS or Android devices.
=> docs: add instructions on using specific devices

dev-client/jest/integration/setup.ts
Add trailing slash to graphQLEndpoint.
=> fix: add trailing slash to graphQLEndpoint

dev-client/app.config.ts, dev-client/package-lock.json, dev-client/package.json
=> fix: bump version number to 1.0.2

dev-client/package-lock.json, dev-client/package.json
=> build: bump @types/react to 18.3.5

dev-client/package-lock.json, dev-client/package.json
bump @testing-library/react-native to 12.6.1.
=> build: bump @testing-library/react-native to 12.6.1

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context to 4.11.0.
=> build: update react-native-safe-area-context to 4.11.0

dev-client/package-lock.json, dev-client/package.json
=> build: update expo to 51.0.32

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.15.1

dev-client/package-lock.json, dev-client/package.json
update react-test-renderer to 18.3.1.
=> build: update react-test-renderer to 18.3.1

dev-client/package-lock.json, dev-client/package.json
=> build: update typescript to 5.6.2

dev-client/package-lock.json, dev-client/package.json
update @rnmapbox/maps to 10.1.31
=> build: update @rnmapbox/maps to 10.1.31

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/cli-doctor to 14.1.1.
=> build: update @react-native-community/cli-doctor to 14.1.1

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native to 12.7.2
=> build: update @testing-library/react-native to 12.7.2

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 5.33.0.
=> build: update @sentry/react-native to 5.33.0

dev-client/package-lock.json, dev-client/package.json
update @types/react to 18.3.7.
=> build: update @types/react to 18.3.7

dev-client/package-lock.json, dev-client/package.json
update expo-media-library to 16.0.5.
=> build: update expo-media-library to 16.0.5

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/netinfo to 11.4.0.
=> build: update @react-native-community/netinfo to 11.4.0

dev-client/package-lock.json, dev-client/package.json
update @react-native/babel-preset to 0.75.3.
=> build: update @react-native/babel-preset to 0.75.3

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.15.2.
=> build: update react-native-reanimated to 3.15.2

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.7.1.
=> build: update react-native-svg to 15.7.1

dev-client/jest.unit.config.js, dev-client/package-lock.json, dev-client/package.json, dev-client/src/config/featureFlags.test.ts, dev-client/src/config/featureFlags.ts, dev-client/src/config/index.ts, dev-client/src/hooks/useStorage.ts, dev-client/src/navigation/navigators/RootNavigator.tsx, dev-client/src/persistence/kvStorage.test.ts, dev-client/src/persistence/kvStorage.ts, dev-client/src/screens/WelcomeScreen.tsx
Consolidates our usage of MMKV.
Fixes #2161
Everything should work the same.
=> refactor: consolidate MMKV usage

dev-client/package-lock.json, dev-client/package.json
update shared client to f5d594a
=> build: update shared client to f5d594a

dev-client/app.config.ts, dev-client/package-lock.json, dev-client/package.json
=> fix: update version to 1.1

dev-client/__tests__/snapshot/__snapshots__/LocationDashboardScreen-test.tsx.snap, dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
Show privacy icon on sites associated with projects
Addresses #1807.
=> feat: show privacy icon on sites associated with projects

dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap, dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx, dev-client/src/translations/en.json
Update text for vertical and surface cracks.
Addresses #976
=> fix: update text for vertical and surface cracks

dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap, dev-client/src/screens/SoilScreen/components/EditDepthModal.tsx, dev-client/src/translations/en.json
- update input text labels and descriptions
- add input description to soil depth sheet
Addresses #2225
=> fix: update input text labels and descriptions

dev-client/babel.config.js, dev-client/index.js, dev-client/react-native.config.js
add copyright notices to JS config files
=> docs: add copyright notices to JS config files

.github/dependabot.yml
=> fix: add react group to dependabot

dev-client/package-lock.json, dev-client/package.json
update dependencies from branch.
=> build: update dependencies from branch

dev-client/app.config.ts, dev-client/metro.config.js, dev-client/package-lock.json, dev-client/package.json
Update sentry metro and app config.
=> fix: update sentry configuration

dev-client/src/translations/index.ts
Import  intl-pluralrules polyfill.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2303
=> fix: add intl-pluralrules import

dev-client/package-lock.json, dev-client/package.json
update @gorhom/bottom-sheet to 5.0.2.
=> build: update @gorhom/bottom-sheet to 5.0.2

dev-client/package-lock.json, dev-client/package.json
=> build: update expo to 51.0.38

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/src/components/sheets/InfoSheet.tsx
flex InfoSheet heading content — avoids pushing close button offscreen
Addresses #2299.
=> fix: flex InfoSheet heading content

dev-client/package-lock.json, dev-client/package.json
update @react-native-community/cli-doctor to 15.1.2.
=> build: update @react-native-community/cli-doctor to 15.1.2

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.16.1.
=> build: update react-native-reanimated to 3.16.1

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.8.0.
=> build: update react-native-svg to 15.8.0

dev-client/package-lock.json, dev-client/package.json
update @sentry/core to 8.38.0.
=> build: update @sentry/core to 8.38.0

dev-client/package-lock.json, dev-client/package.json
update react-native-mmkv-storage to 0.11.2.
=> build: update react-native-mmkv-storage to 0.11.2

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler to 2.21.0.
=> build: update react-native-gesture-handler to 2.21.0

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.9.0.
=> build: update react-native-svg to 15.9.0

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler to 2.21.1.
=> build: update react-native-gesture-handler to 2.21.1

dev-client/package-lock.json, dev-client/package.json
update @gorhom/bottom-sheet to 5.0.6.
=> build: update @gorhom/bottom-sheet to 5.0.6

dev-client/package-lock.json, dev-client/package.json
update @sentry/react-native to 6.2.0
=> build: update @sentry/react-native to 6.2.0

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
change data to observations throughout app
Addresses #2469, #2465, #1150, #2472, #2467, #2473, #2466, #2464, #2468.
=> fix: change data to observations throughout app

dev-client/src/screens/LocationScreens/components/soilInfo/LocationScoreDisplay.tsx
Round location score distance to nearest meter.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2496
=> fix: round location score distance to nearest meter

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.16.6

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 23.16.8

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated to 3.16.2.
=> build: update react-native-reanimated to 3.16.2

dev-client/package-lock.json, dev-client/package.json
update react-native-screens to 4.3.0
=> build: update react-native-screens to 4.3.0

dev-client/package-lock.json, dev-client/package.json
update react-native-tab-view to 4.0.3.
=> build: update react-native-tab-view to 4.0.3

dev-client/package-lock.json, dev-client/package.json
=> build: bump typescript to 5.7.2

dev-client/package-lock.json, dev-client/package.json
update react-native-tab-view to 4.0.4.
=> build: update react-native-tab-view to 4.0.4

dev-client/src/translations/index.ts
=> fix: simplify translation object

dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/package-lock.json, dev-client/package.json, dev-client/src/screens/SitesScreen/components/LatLngDetail.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json, dev-client/src/util.ts
- update strings to work with i18next 24 (get rid of `lng` placeholder). see https://github.com/i18next/i18next/issues/2264
- update i18next to 24.0.2
=> fix: update strings to work with i18next 24

dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/src/screens/ProjectSitesScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Correct delete modal string for sites.
Addresses #2472.
=> fix: correct delete modal string for sites

dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
Disable site public/private radio buttons when offline
Addresses #2370.
=> fix: disable site public/private radio buttons when offline

dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/src/screens/LocationScreens/components/soilId/SiteSlopeDataSection.tsx, dev-client/src/translations/en.json
update slope steepness section layout
- move Enter Steepness button below slope data
- [change button label Add slope -> Enter steepness](https://github.com/techmatters/terraso-mobile-client/commit/232a94d121742790c8d3b20730a08fbe90b350d3)
Addresses #2515
=> fix: update slope steepness section layout

dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/src/screens/LocationScreens/components/soilId/SiteDataSection.tsx, dev-client/src/screens/LocationScreens/components/soilId/SiteSoilCracksSection.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Add a soil cracking section to the site data screen.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1888
=> feat: add soil cracking section to site data

dev-client/locales/po/en.po, dev-client/locales/po/es.po, dev-client/src/App.tsx, dev-client/src/screens/LocationScreens/components/soilId/SoilIdMatchesSection.tsx, dev-client/src/screens/LocationScreens/components/soilId/messageBoxes/OfflineMessageBox.tsx, dev-client/src/screens/LocationScreens/components/soilInfo/PropertiesScoreDisplay.tsx, dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx, dev-client/src/screens/SiteNotesScreen/SiteNotesScreen.tsx, dev-client/src/screens/SiteNotesScreen/components/SiteNoteCard.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Disable adding and editing of notes when offline.
Note: this builds on https://github.com/techmatters/terraso-mobile-client/pull/2566 and should be rebased after `fix/soil-properties` is merged..
Addresses #2374.
=> fix: disable adding and editing of notes when offline

dev-client/locales/po/en.po, dev-client/src/screens/SitesScreen/components/EmptySiteMessage.tsx, dev-client/src/screens/SitesScreen/components/SiteListBottomSheet.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update empty sites sheet with new design.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2517
=> fix: redesign empty sites sheet

dev-client/package-lock.json, dev-client/package.json
=> build: bump yup to 1.5.0

dev-client/package-lock.json, dev-client/package.json
bump @testing-library/react-native@12.9.0.
=> build: bump @testing-library/react-native@12.9.0

dev-client/package-lock.json, dev-client/package.json
=> build: bump prettier to 3.4.2

dev-client/package-lock.json, dev-client/package.json
bump @react-native-community/cli-doctor to 16.0.0.
=> build: bump @react-native-community/cli-doctor to 16.0.0

dev-client/package-lock.json, dev-client/package.json
bump react-native-reanimated to 3.16.3.
=> build: bump react-native-reanimated to 3.16.3

dev-client/package-lock.json, dev-client/package.json
bump react-native-tab-view to 4.0.5.
=> build: bump react-native-tab-view to 4.0.5

dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
bump react-native-pager-view 6.6.1.
=> build: bump react-native-pager-view 6.6.1

dev-client/package-lock.json, dev-client/package.json
bump react-native-svg to 15.10.1.
=> build: bump react-native-svg to 15.10.1

dev-client/package-lock.json, dev-client/package.json
bump react-native-safe-area-context to 5.0.0.
=> build: bump react-native-safe-area-context to 5.0.0

dev-client/src/theme.ts, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Correct alert error text color; add missing period to offline error text.
Follow-on fix to #2373.
=> fix: correct alert error text color; add missing period to offline error text

dev-client/package-lock.json
update dependencies from dependabot.
=> build: update dependencies from dependabot

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated@3.16.5.
=> build: update react-native-reanimated@3.16.5

dev-client/src/components/content/info/landpks/LandPKSInfoContent.tsx, dev-client/src/screens/SitesScreen/components/EmptySiteMessage.tsx, dev-client/src/screens/SitesScreen/components/GetStartedMessage.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update info sheet design
Addresses #2564.
=> fix: update info sheet design

dev-client/src/components/buttons/DeleteButton.tsx, dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/SignOutItem.tsx, dev-client/src/theme.ts
Disable sign out button action when offline.
Addresses #2376, #2371.
=> fix: disable sign out button action, site settings when offline

dev-client/src/screens/SitesScreen/SitesScreen.tsx
Open temporary location callout when My Location button is pressed.
Addresses #2563.
=> feat: open callout when My Location button is pressed

dev-client/src/screens/SitesScreen/components/search/MapSearchOfflineAlertBox.tsx
Change text color for offline search box per design request.
#2367
Search in offline mode and check text color.
=> fix: change text color for offline search box

dev-client/package-lock.json, dev-client/package.json
weekly dependabot dependencies update.
=> build: weekly dependabot update

dev-client/package-lock.json, dev-client/package.json
Update dependencies from dependabot.
=> build: dependabot updates

dev-client/src/components/inputs/image/ImagePicker.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update the soil color image picker buttons to match designs (see ticket).
#2704
Open the soil color image selector and verify button appearances.
=> feat: update soil color photo buttons

dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectRoleScreen.tsx
Update button usage on `AddUserToProjectRoleScreen` to match design.
#2710
Verify buttons when selecting the role for a new user to a project.
=> feat: Update "add user" role screen buttons

dev-client/src/components/messages/AlertMessageBox.tsx, dev-client/src/components/messages/ErrorMessageBox.tsx, dev-client/src/theme.ts
Make alert icon 24px.
Courtney approved this size.
Addresses #2366.
=> fix: make alert icon 24px

dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update name of Enter Properties button on Soil Data Screen.
=> fix: update name of Enter Properties button

dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx
Update the manual steepness button to be a `DialogButton` with "save".
#2700
Verify appearance of manual steepness entry dialog.
=> feat: update manual steepness dialog button

dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update layout and behavior associated with site settings screen buttons.
#2707
Verify appearance of site settings screen. Verify that title does not change with text entry until user saves changes.
=> feat: update to button behavior / layout for site settings screen

dev-client/package-lock.json, dev-client/package.json
bump react-native-reanimated to 3.16.6.
=> build: bump react-native-reanimated to 3.16.6

dev-client/package-lock.json, dev-client/package.json
bump react-native-autocomplete-input to 5.5.5.
=> build: bump react-native-autocomplete-input to 5.5.5

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
bump react-native-screens to 4.4.0.
=> build: bump react-native-screens to 4.4.0

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native@13.0.0.
=> build: update @testing-library/react-native@13.0.0

dev-client/package-lock.json, dev-client/package.json
=> build: update @sentry/core@8.48.0

dev-client/package-lock.json, dev-client/package.json
update @react-navigation/native@7.0.14.
=> build: update @react-navigation/native@7.0.14

dev-client/src/screens/UserSettingsScreen/UserSettingsScreen.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/DeleteAccountItem.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/HelpItem.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/LinkItem.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/LinkItems.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/PrivacyItem.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/SignOutItem.tsx, dev-client/src/screens/UserSettingsScreen/components/menu/TosItem.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Change styling and add requested URL link items to user settings screen.
#2637
Open settings screen and visit links.
=> feat: updates to user settings screen

dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update soil cracking screen text
Addresses #2525.
=> fix: update soil cracking screen text

dev-client/src/screens/SoilScreen/components/EditSiteSoilDepthPreset.tsx
rework depths menu screen
(1) remove label
(2) remove save button
(3) trigger confirmation dialog + change when radio button is pressed
Addresses #2701.
=> fix: rework depths menu screen

dev-client/src/translations/en.json, dev-client/src/translations/es.json
Updates the website link from landpotential.org to landpks.terraso.org
Fixes, once QA'd, https://github.com/techmatters/terraso-mobile-client/issues/2633
=> feat: update website link

dev-client/src/components/dialogs/ErrorDialog.tsx, dev-client/src/constants.ts, dev-client/src/hooks/useStorage.ts, dev-client/src/navigation/navigators/RootNavigator.tsx, dev-client/src/screens/WelcomeScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Update interstitial for 1.2
• new bullets
• refactor/use a constant for key / flag to show/hide window
• add ToS and PP
Addresses #2302. Also fixes capitalization of sign out on user settings screen (#2637).
=> fix: update interstitial for 1.2

.github/dependabot.yml
Disable non-security dependency updates for now.
=> chore: disable non-security dependency updates for now

dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx, dev-client/src/translations/en.json
Soil cracking screen (#2525):
- update text
- ensure done button is aways enabled
Settings screen (#2637)
- sentence case "Sign out"
- sentence case "Delete account"
=> fix: update soil cracking and settings screen

dev-client/src/components/AddDepthModal.tsx, dev-client/src/screens/SoilScreen/components/EditDepthModal.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
• edit depth: update title to use label (#2703)
• edit depth: move delete button (#2703)
• edit depth: don't apply toggles until save (#2703)
• edit depth: disable save button if form is unchanged (#2702)
• add depth: disable add button if form is blank (#2702)
=> fix: improve depth screens

dev-client/src/config/featureFlags.test.ts, dev-client/src/config/featureFlags.ts
Default enables the offline feature flag! Not ready to merge it quite yet, but satisfying to make the PR :)
Related to https://github.com/techmatters/terraso-mobile-client/issues/2850
The resulting prod build should have offline features enabled!
=> feat: enable offline feature flag! 🎉

dev-client/package-lock.json, dev-client/package.json
update eslint-config-prettier@10.0.1.
=> build: update eslint-config-prettier@10.0.1

dev-client/package-lock.json, dev-client/package.json
update react-native-svg@15.11.1.
=> build: update react-native-svg@15.11.1

dev-client/app.config.ts, dev-client/package-lock.json, dev-client/package.json
Bump version to 1.3 after releasing 1.2
=> chore: bump version to 1.3

dev-client/package-lock.json, dev-client/package.json
update @babel/core@7.26.7 @babel/preset-env@7.26.7 @babel/runtime@7.26.7.
=> build: update @babel/core@7.26.7 @babel/preset-env@7.26.7 @babel/runtime@7.26.7

dev-client/package-lock.json, dev-client/package.json
install @gorhom/bottom-sheet@5.1.0.
=> build: install @gorhom/bottom-sheet@5.1.0

dev-client/package-lock.json, dev-client/package.json
update @ianvs/prettier-plugin-sort-imports@4.4.1.
=> build: update @ianvs/prettier-plugin-sort-imports@4.4.1

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next@24.2.2

dev-client/package-lock.json, dev-client/package.json
=> build: update @types/lodash@4.17.15

dev-client/package-lock.json, dev-client/package.json
update @testing-library/react-native@13.0.1.
=> build: update @testing-library/react-native@13.0.1

dev-client/package-lock.json, dev-client/package.json
update react-native-pager-view@6.7.0
=> build: update react-native-pager-view@6.7.0

dev-client/package-lock.json, dev-client/package.json
=> build: update react-devtools@6.1.0

dev-client/package-lock.json, dev-client/package.json
update react-native-autocomplete-input@5.5.6.
=> build: update react-native-autocomplete-input@5.5.6

dev-client/package-lock.json, dev-client/package.json
update react-native-gesture-handler@2.23.0.
=> build: update react-native-gesture-handler@2.23.0

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/package-lock.json, dev-client/package.json
update react-native-paper@5.13.1
=> build: update react-native-paper@5.13.1

dev-client/package-lock.json, dev-client/package.json
update react-native-safe-area-context@5.2.0
=> build: update react-native-safe-area-context@5.2.0

dev-client/package-lock.json, dev-client/package.json
update react-native-reanimated@3.16.7.
=> build: update react-native-reanimated@3.16.7

dev-client/package-lock.json, dev-client/package.json
=> build: update expo@~52.0.33

dev-client/package-lock.json, dev-client/package.json
=> build: update react-devtools@6.1.1

dev-client/package-lock.json, dev-client/package.json
update @babel/core@7.26.8 @babel/preset-env@7.26.8.
=> build: update @babel/core@7.26.8 @babel/preset-env@7.26.8

dev-client/package-lock.json, dev-client/package.json, dev-client/src/screens/LocationScreens/components/LocationSoilIdCard.tsx
update prettier to 3.5.0 and reformat one file.
=> build: update prettier to 3.5.0

dev-client/package-lock.json, dev-client/package.json
update @gorhom/bottom-sheet@5.1.1.
=> build: update @gorhom/bottom-sheet@5.1.1

dev-client/__tests__/integration/app/launch.test.tsx, dev-client/__tests__/integration/store/sync/PullDispatcher.test.tsx, dev-client/__tests__/integration/store/sync/PushDispatcher.test.tsx, dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/LoginScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SlopeScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap, dev-client/jest.integration.config.js, dev-client/jest/integration/setup.ts, dev-client/jest/integration/utils.tsx, dev-client/src/App.tsx, dev-client/src/app/AppContent.tsx, dev-client/src/app/AppWrappers.tsx, dev-client/src/app/Sentry.tsx, dev-client/src/context/HeaderHeightContext.tsx, dev-client/src/screens/LoginScreen.tsx, dev-client/src/screens/SitesScreen/SitesScreen.tsx, dev-client/src/screens/WelcomeScreen.tsx, dev-client/src/store/index.ts
Makes a bunch of changes to our integration test set up to enable us to write whole-app integration tests for core workflows. Here we're adding tests for launching the app as a proof of concept!
The first commit, "refactor: split up App.tsx", can be reviewed independently. It moves most of the code in `App.tsx` into four different files: `AppWrapper.tsx`, `AppContent.tsx`, `Sentry.tsx`, and `HeaderHeightContext.tsx`. The remaining commits are more or less all adding/changing mocks and adding tests.
I would like to file some follow-up tech debt tickets before merging:
- one major component of the app which is still not very integration testable right now is the home screen map. `@rnmapbox/maps` doesn't seem to come with reasonable mocks by default, so we'll need to create our own if we …
=> test: app launch conditions

.husky/pre-commit, Makefile, dev-client/package-lock.json, dev-client/package.json, scripts/pre-commit.sample
Description
use husky for pre-commit linting
only lint changed files
=> build: use husky for pre-commit linting

dev-client/package-lock.json, dev-client/package.json
=> build: update i18next to 25.1.1

dev-client/package-lock.json, dev-client/package.json
=> build: update lint-staged to 15.5.2

dev-client/package-lock.json, dev-client/package.json
update @types/lodash to 4.17.16
=> build: update @types/lodash to 4.17.16

dev-client/package-lock.json, dev-client/package.json
=> build: update munsell to 1.1.6

dev-client/package-lock.json, dev-client/package.json
=> build: update prettier to 3.5.3

dev-client/package-lock.json, dev-client/package.json
update eslint-config-prettier to 10.1.3
=> build: update eslint-config-prettier to 10.1.3

dev-client/package-lock.json, dev-client/package.json
update @expo/vector-icons to 14.1.0.
=> build: update @expo/vector-icons to 14.1.0

dev-client/package-lock.json, dev-client/package.json
update @babel/core@7.27.1 @babel/preset-env@7.27.2 @babel/preset-typescript@7.27.1 @babel/runtime@7.27.1
=> build: update @babel/core@7.27.1 @babel/preset-env@7.27.2 @babel/preset-typescript@7.27.1 @babel/runtime@7.27.1

dev-client/package-lock.json, dev-client/package.json
update react-native-svg to 15.11.2
=> build: update react-native-svg to 15.11.2

dev-client/package-lock.json, dev-client/package.json
update react-native-svg-transformer to 1.5.1
=> build: update react-native-svg-transformer to 1.5.1

dev-client/package-lock.json, dev-client/package.json
update react-native-pager-view to 6.7.1
=> build: update react-native-pager-view to 6.7.1

dev-client/package-lock.json, dev-client/package.json
- Update the commit hash for the client-shared dependency, after updating its commit hash for its backend dependency
Required for https://github.com/techmatters/terraso-backend/issues/1618
=> build: bump terraso-client-shared and UUID

dev-client/src/constants.ts, dev-client/src/screens/WelcomeScreen.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
=> fix: updated WelcomeScreen (#1305)

dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap, dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap, dev-client/src/components/content/info/privacy/DataPrivacyContent.tsx, dev-client/src/translations/en.json, dev-client/src/translations/es.json
Add text related to t-o-s and privacy policy
=> fix: add link to terms-of-service and update data privacy link in DataPrivacyContent (#2663)

dev-client/src/app/AppWrappers.tsx, dev-client/src/navigation/components/SiteTabJump.tsx, dev-client/src/navigation/components/SiteTabJumpProvider.tsx, dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx, dev-client/src/screens/LocationScreens/components/soilId/SiteSoilPropertiesDataSection.tsx
I thought I already created this PR, but I don't see it so adding it again.
Basically avoid ever-growing navigation stack in particular case (bug #2936 has details).
The code turned out a bit more involved than expected.  I am happy to explain why in a meeting if that helpful.
=> fix: nav stack changes 2936

dev-client/docs/Offline.md
Adds a primer on our offline architecture to the documentation.
=> docs: offline primer
