- dev-client/App.tsx
- dev-client/__tests__/SitesMap-test.tsx
- dev-client/android/app/build.gradle
- dev-client/components/Login.tsx
- dev-client/components/SiteMap.tsx
- dev-client/datatypes/sites.ts
- dev-client/package-lock.json
- dev-client/package.json
- dev-client/theme.ts
This is a bit of a messy commit, as I was trying out a bunch of new libraries to try and get this to work. The main changes are:
- Moved the map component into it's own separate component
- Added a vector icon library to display icons that match the mockups
- Tried doing some tests, but I think we need to install some coco pods through xcode or something. I will create a chore task and try and get someone to do this.
- Ran prettier on everything, so there's a lot of noise from just styling edits
- Displayed the user location on the map, which requires asking the user for permission on newer versions of Android.
I started working on this issue because I realized that the login for mobile is more difficult than I anticipated (see #44 for details). It would be nice to have some mockups …
> feat: Update map view to display a beautiful marker

- .github/workflows/build.yml
Add [buildcache](https://github.com/marketplace/actions/buildcache-action) to the ios build step
```
- uses: mikehardy/buildcache-action@v2
```
> chore: add buildcache to iOS build step

- .gitignore
Move gitignore to top level of repository. Avoids .DS_Store files in root showing up in repo.
> chore: move gitignore to top level of repository

- dev-client/metro.config.js
- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/screens/AppScaffold.tsx
- dev-client/src/screens/index.ts
I was getting the following warning when I ran `npm run start`:
warn From React Native 0.72, your metro.config.js file should extend'@react-native/metro-config'.
Metro would then crash. I obliged, and this commit is the result. Seems to fix things.
> fix: Update metro config

- dev-client/ios/Podfile.lock
- dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj
- dev-client/react-native.config.js
No longer manually add fonts to build phase; have React Native Vector Icons automatically include them.
Note: this ends up bundling extra `ttf` files. Normally, we would specify just the fonts we want, but since this is temporary until the icons go in the Mapbox stylesheet.
> fix: automatically include React Native fonts

- dev-client/src/config/index.ts
- dev-client/src/screens/AppScaffold.tsx
- dev-client/src/screens/HomeScreen.tsx
The app previously would always load into the login screen, and then load the home screen if the user was already logged in. Now the app will directly load the home screen if the user is already logged in, without briefly showing the login screen.
This fixes the bug in the description, but I am hoping it will also fix #257. I am not able to reproduce #257 on my devices so we will have to wait until we can push some new releases to find out.
> fix: dont flicker login screen on startup when logged in

- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/theme.ts
Fixes #266 
Fixes #221 
Map pins should now be a reasonable size, and the non-site location popover matches the design and contains placeholder data.
> feat: update home screen map to better match design

- dev-client/src/components/common/Icons.tsx
Previously, only the small icon portion of the bottom navigation buttons was pressable, which made it easy to miss the button and need to press it several times to effect a page navigation. With this change the entire button, including label and a 1 padding box around the button is pressable, and I am not finding I need to tap several times anymore.
> fix: make entire bottom nav button pressable

- .github/workflows/android_build.yml
- .github/workflows/ios_build.yml
Don't commit version bumps to main — this will fail, as main is protected.
> fix: don't commit version bumps to main

- dev-client/src/components/home/MapSearch.tsx
- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/screens/HomeScreen.tsx
Allows toggling the map style between streets and satellite on the home screen. This implementation has an annoying problem where the first time the button is toggled, the Mapbox library raises an error even though everything functions totally fine. So I'm tempted to merge as is and file a backlog issue to figure the error message out, since it won't be visible outside of dev builds. (I think?). Thoughts?
Fixes #47
> feat: toggle map styles on home screen

- dev-client/src/components/home/BottomSheet.tsx
- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/components/sites/CreateSiteView.tsx
- dev-client/src/components/sites/LocationDashboardScreen.tsx
- dev-client/src/screens/CreateSiteScreen.tsx
- dev-client/src/screens/HomeScreen.tsx
**NOTE: THIS PR IS BASED ON https://github.com/techmatters/terraso-mobile-client/pull/318 TO AVOID MERGE CONFLICTS. MAKE SURE THAT PR GETS MERGED AND BASE BRANCH IS UPDATED TO MAIN BEFORE MERGING THIS PR.**
Creating a site from the bottom sheet's button now also uses the dropped location pin's coords if available.
Fixes #315
> feat: bottom sheet site create uses dropped pin's coordinates

- .github/workflows/build-shared-ios.yml
- .github/workflows/ios_build.yml
- dev-client/ios/Podfile.lock
- dev-client/ios/Terraso LandPKS.xcodeproj/project.pbxproj
- dev-client/ios/Terraso LandPKS/Info.plist
- dev-client/package-lock.json
- dev-client/package.json
Use main branch of react-native-gesture-handler. Allows site popover to be closed.
See:
https://github.com/techmatters/terraso-mobile-client/issues/305 https://github.com/rnmapbox/maps/issues/2880#issuecomment-1630091579
Fixes #305.
> fix: use main branch of react-native-gesture-handler + fix build workflow

- .github/workflows/build.yml
Updates the `build.yml` file to use the default values for what types of pull request events trigger a build. We had specified the `edited` event which would cause a rebuild if the PR's title or body changed.
This PR should still trigger a build run. But if the title is edited a new build run should not be triggered.
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
- https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
> fix: dont rerun build action on PR title/body edit

- dev-client/src/components/common/ProgressCircle.tsx
- dev-client/src/components/projects/ProjectSitesTab.tsx
Updates the site card in the project sites list to use the same component as on the home screen.
Fixes (once QA'd) #323
> feat: use updated site card design/component for project sites list

- dev-client/src/components/home/BottomSheet.tsx
- dev-client/src/screens/HomeScreen.tsx
When clicking a site card's map icon, the bottom sheet will  collapse as we're panning the map to the site.
Fixes (once QA'd) #306
> feat: collapse bottom sheet when showing site

- dev-client/src/screens/AppScaffold.tsx
Hide back button titles on iOS. Matches Android behaviour.
Fixes #339.
> fix: hide back button titles on iOS

- dev-client/src/components/sites/CreateSiteView.tsx
Use numeric keyboard for lat/long fields
Fixes #328.
> fix: use numeric keyboard for lat/long fields

- dev-client/android/app/build.gradle
- dev-client/android/app/proguard-rules.pro
Follows the
[react-native config docs](https://github.com/luggit/react-native-config#problems-with-proguard) to reactivate Proguard. This lets of shave a few MB off of the final Android app side.
I deactivated in the first place to fix the problem described in the link above.
Fixes #....
> fix: reactivate proguard

- dev-client/src/components/home/MapSearch.tsx
- dev-client/src/components/home/SiteMap.tsx
This PR updates the location search behaviour:
1) Respond better to when the user closes the keyboard
2) Activates flex layout on the autocomplete itself, which might fix issues with the iOS display.
Fixes #....
> fix: Small changes to search behaviour

- dev-client/src/screens/ScreenScaffold.tsx
Use location pin icon for 'home' in bottom toolbar
Fixes #353.
> fix: use location pin icon for 'home' in bottom toolbar

- dev-client/src/App.tsx
Hide SSRProvider warning:
```
In React 18, SSRProvider is not necessary and is a noop. You can remove it from your app.
```
NativeBase is no longer being updated so this warning won't be fixed.
> fix: hide SSRProvider warning

- dev-client/src/components/sites/CreateSiteView.tsx
Changes the CreateSiteView to pass a function to the setMutationInput function. This ensures that the most current state is being used and we don't get stale state, which caused this bug.
The ultimate goal is to replace this custom form updating with Formik after we've set up a few unit tests, but as we are getting ready for usability testing I've opted for the simplest solution.
Fixes #....
> fix: Don't reset site name on privacy change

- dev-client/src/components/common/Map.tsx
- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/theme.ts
I think what is happening here is we're working around a bug in rnmapbox where they ignore the `scale` attribute of RN `ImageSource`s passed into the `Mapbox.Images` component on Android only. We do this by selectively multiplying the icon size by the pixel ratio on Android only. I'd like paul to confirm it looks good on his iOS dev setup before merging, but i think we still won't know until we push a release with this fix.
Fixes (hopefully, once QA'd) #192, #367, #316, and #365
Map icons should be the correct size and not pixelated on all platforms.
> fix: map icon size and resolution

- dev-client/src/components/home/MapSearch.tsx
- dev-client/src/components/home/mapSearch.ts
Uses the Web API [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController) to cancel requests that are still pending when a previous request is triggered. Previously this would often happen with short strings, where the search request for a shorter string takes longer than a longer string.
- Request 1 triggered.
- Request 2 triggered.
- Request 2 completes.
- Request 1 completes.
The results of Request 1 would overwrite Request 2.
This was particularly a problem when trying to reset the search results, because setting the react state takes much less time than making a HTTP request. So it would be something like:
- Request triggered for query of length 2
- Suggestions cleared when user continues deleting
- Request completes, and suggestions set …
> fix: Clear search box when search query empty

- dev-client/src/components/sites/LocationDashboardScreen.tsx
Remove empty (`''`) left margin on site page. Removes warning message.
Fixes #397.
> fix: remove empty left marrgin

- dev-client/src/components/sites/CreateSiteView.tsx
- dev-client/src/model/map/mapSlice.ts
- dev-client/src/screens/AppScaffold.tsx
- dev-client/src/screens/CreateSiteScreen.tsx
- dev-client/src/screens/HomeScreen.tsx
Moves the logic that updates user's location to the root of the app, and modifies the create site form to keep the lat/lon fields updated as the user moves.
Fixes #256
Latitude/longitude field of create site form should update as user moves around.
> fix: update lat/lon of create site form as user's location changes

- dev-client/src/components/common/Card.tsx
- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/screens/HomeScreen.tsx
Site pins on the home screen are now clustered when they are close together. Clicking a cluster will zoom in on it enough to split up the cluster when zoomed out, or show a list if already zoomed in a lot. Clicking a list item will close the list and open the callout for that site. Also resolved some of the things from #333 and #405 while I was monkeying around in the map code.
Limitations: 
- uses a circle for clusters instead of the chip from design. using the chip would require pre-loading images of the chip without text and manually positioning text on the chip using the janky mapbox style API while accounting for platform differences in resolution etc, which is possible but too much effort for a first PR or maybe for MVP
- i couldn't figure out how to make the list scrollable because …
> feat: home screen site pin clustering

- dev-client/src/components/sites/CreateSiteView.tsx
This allows me to create a site locally, and logically makes sense. However I'm not sure why Typescript does not pick up on locationSource being included in the input to the GraphQL call here. @shrouxm any idea?
Fixes #....
> fix: Don't submit locationSource on create site

- dev-client/src/components/common/FreeformTextInput.tsx
This input is intended for the add user to project screen. It will just encapsulate the logic of validating the user emails exists and displaying an error message if invalid. In the future the error message may be more complex, like displaying a modal or something, so I've decided to make this a whole separate component.
Fixes #....
> feat: Add free form text input

- dev-client/src/hooks/index.tsx
This hook just returns a reactive value that is true when the keyboard is open, and false when it is closed. I'm using it to hide the submit button on a form when the keyboard is open, because I kept on accidentally submitting while testing - maybe it will be useful elsewhere.
Fixes #....
> feat: Add hook for when keyboard is open

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/components/common/Form.tsx
- dev-client/src/components/common/Modal.tsx
- dev-client/src/components/common/SpeedDial.tsx
- dev-client/src/components/dataInputs/AddIntervalModal.tsx
- dev-client/src/components/dataInputs/EditIntervalModal.tsx
- dev-client/src/components/dataInputs/IntervalForm.tsx
- dev-client/src/components/dataInputs/SlopeScreen.tsx
- dev-client/src/components/dataInputs/SoilScreen.tsx
- dev-client/src/components/projects/CreateProjectView/index.tsx
- dev-client/src/components/projects/ProjectInputTab.tsx
- dev-client/src/components/projects/ProjectPreviewCard.tsx
- dev-client/src/components/projects/ProjectSitesTab.tsx
- dev-client/src/components/projects/ProjectTabs.tsx
- dev-client/src/components/projects/constants.ts
- dev-client/src/components/sites/LocationDashboardScreen.tsx
- dev-client/src/components/sites/LocationDashboardView.tsx
- dev-client/src/components/sites/SiteSettingsScreen.tsx
- dev-client/src/constants.ts
- dev-client/src/screens/AppScaffold.tsx
- dev-client/src/screens/HomeScreen.tsx
- dev-client/src/screens/ProjectListScreen.tsx
- dev-client/src/screens/TabBar.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Scaffolds the site dashboard so it is ready for future data inputs work. Creates the site tabs, and ability to add/edit a site's depth intervals so that all data inputs can be navigated to. Still needs a bunch more work, but wanted to make the code available now since it's interrelated with the relevant client-shared/backend PRs and paul asked me to! depends on https://github.com/techmatters/terraso-client-shared/pull/105 and https://github.com/techmatters/terraso-backend/pull/843
Fixes #395 
Fixes #432
Fixes #396 
Fixes #456
Limitations:
- project inputs screen raises warnings (but is functional if not beautiful)
- new formswitch component raises warnings (but is functional)
- project required data inputs are not wired to individual sites yet
- "apply to all intervals" checkbox on …
> feat: site dashboard scaffolding!

- dev-client/src/components/common/Card.tsx
- dev-client/src/components/home/BottomSheet.tsx
- dev-client/src/components/home/SiteMap.tsx
- dev-client/src/components/home/SiteMapCallout.tsx
- dev-client/src/components/home/TemporarySiteCallout.tsx
- dev-client/src/components/sites/SiteCard.tsx
- dev-client/src/screens/HomeScreen.tsx
This is a collection of small updates to the home screen map UI/behavior:
- Fixes an issue where initial camera move didn't fire on iOS
- Sets the default map location to the USA
- Adds a drop shadow to the location popovers
- Adds padding to separate the site name header from the popover close button
Fixes #499
Refs #436
> fix: home screen map behavior

- dev-client/src/components/common/FreeformTextInput.tsx
- dev-client/src/components/projects/AddUserToProjectScreen/index.tsx
Adjust keyboard settings for email address:
* disable capitalization
* enable autofill
* use email address-optimized keyboard
Note sure if this works with `FreeformTextInput` as-is or needs to be passed in as XYZProps.
> fix: adjust keyboard settings for email address

- dev-client/src/components/home/CustomUserLocation.tsx
- dev-client/src/components/home/MapSearch.tsx
- dev-client/src/components/home/SiteMap.tsx
- Adds search bar button to clear search input 
- If a popover is open and user taps on the map, close the popover without opening another one
- Allow taps on the map through the transparent parts of the MapSearch component
- Allow users to open site popovers that are near or on to user's location. This was a tricky one; there's a known issue with rnmapbox where the blue UserLocation circle prevents taps on anything nearby. The recommended workaround, as far as I can tell, is to override the default UserLocation component and define a relevant belowLayerID (in our case, 'sitesLayer'). https://github.com/rnmapbox/maps/issues/241
- Allow users to open location popover near or on user's location. Mapbox's default UserLocation onPress handler doesn't have a defined return type, but it does …
> feat: home screen updates

- README.md
> docs: add Java notes to README

- dev-client/android/build.gradle
- dev-client/android/gradle.properties
- dev-client/package-lock.json
* Add Kotlin plugin to avoid warning:
> The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
>This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
>Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
>If the parent project does not need the plugin, add 'apply false' to the plugin line.
>See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
>The Kotlin plugin was loaded in the following projects: ':react-native-gesture-handler', ':rnmapbox_maps'
* Remove version number from gradle plugin to fix debug …
> fix: improve Android build configuration

- dev-client/src/screens/SiteTransferProjectScreen.tsx
- I was having trouble with getting the FlatList to scroll, so I ended up making the search bar component the list header
- This had the effect that everytime the list was updated, by the search bar in the header, the whole list re-renders, closing the keyboard
- Instead, it turns out that the FlatList was not scrolling only because I had wrapped it in a VStack. When I got rid of the VStack, things scrolled!
- So I did that and put the header component back to a separate component.
- In the future it would be good to understand better how the list rendering stuff works - maybe the whole list shouldn't be rerendering every time it is updated?
> fix: Fix project transfer search

- dev-client/src/components/sites/SiteSettingsScreen.tsx
On the site settings screen, hide Team and Archive Site buttons.
Fixes #535.
> fix: Site settings: hide Team and Archive Site buttons

- dev-client/src/components/common/Icons.tsx
- dev-client/src/components/common/ScreenFormWrapper.tsx
- dev-client/src/components/common/infoModals/InfoModal.tsx
- dev-client/src/components/common/infoModals/PrivacyInfoContent.tsx
- dev-client/src/components/projects/CreateProjectView/Form.tsx
- dev-client/src/components/projects/CreateProjectView/index.tsx
- dev-client/src/components/projects/ProjectInputTab.tsx
- dev-client/src/components/sites/CreateSiteView.tsx
- dev-client/src/components/sites/LocationDashboardScreen.tsx
- dev-client/src/components/sites/LocationDashboardView.tsx
- dev-client/src/screens/CreateProjectScreen.tsx
- dev-client/src/screens/CreateSiteScreen.tsx
- dev-client/src/screens/ProjectViewScreen.tsx
- dev-client/src/translations/en.json
Adds an InfoModal bottom sheet for privacy info on various screens.
Fixes #586
1. When creating a site, tap the info (i) button to open the privacy bottom sheet.
2. View the main site dashboard on a created site. If no project has been assigned, you should see radio buttons for privacy. Tap the info button to open the privacy bottom sheet.
3. When creating a project, tap the info button to open the sheet.
4. View the inputs tab on a created project. You should see privacy radio buttons with an info button that opens a bottom sheet.
> feat: create privacy bottom sheet

- dev-client/src/components/home/BottomSheet.tsx
- dev-client/src/screens/ScreenScaffold.tsx
The current implementation of SafeAreaView was not including the bottom insets, so for example an iPhone 15 pro max the tab bar was not being displayed correctly. This PR not only adjust the bottom padding but also adjusts the sites listing initial snap point based on this values.
> fix: Adjusted SafeAreaView to fit on all devices

- dev-client/src/components/common/Form.tsx
- The Formik `onChange` listener expects an event. React native events are synthetic and often do not contain all of the properties of a browser DOM event, which Formik is expecting.
- Changed from using the `onChange` listener, to `setValue`, which should have the correct effect.
- I think this was likely working for selects and text inputs, because there seems to be some custom logic in the Formik code about if a string is passed to `onChange` . I didn't really look into it more though.
- Tested it out with Checkbox, Input and TextArea Form elements to make sure it works
- Also changes the Soil data tab to use the checkbox library instead of the NativeBase one
Related to #502
> fix: Change Form components onChange listener

- dev-client/src/components/projects/ProjectSettingsTab.tsx
Remove archive project button on project settings screen.
Fixes #597.
Redo of https://github.com/techmatters/terraso-mobile-client/pull/598, which was reverted by https://github.com/techmatters/terraso-mobile-client/commit/5b44fbd8f5bd892742c4cf8607ac52b4a979c780.
> fix: hide archive project button

- dev-client/android/settings.gradle
I had to make this change to `android/settings.gradle` to get the app to compile locally, which is required for react native version 0.72+ according to [this thread](https://github.com/facebook/react-native/issues/36643). I was surprised because I assume other things should have been failing without that setting so I'm wondering if I'm missing something? @paulschreiber @david-code
> fix: path in android/settings.gradle

- dev-client/src/screens/HomeScreen/components/SiteFilterModal.tsx
- dev-client/src/screens/HomeScreen/utils/siteFeatureCollection.ts
I stupidly got rid of this when I merged with main. Found an [issue](https://github.com/techmatters/terraso-mobile-client/issues/706) testing this, but I'm not able to reproduce it consistently. QA will be helpful to see if this is an issue that shows up in the deployed app.
> fix: Reintroduce missing project filter

- dev-client/ios/Terraso LandPKS/Info.plist
Allows the iOS app to use a landscape orientation. @paulschreiber or @david-code can you verify that this works by building the iOS app with this change, navigating to the slope meter screen, and confirming that it displays in landscape orientation?
Fixes #763 
Landscape orientation should work on iOS.
> fix: support landscape orientation on iphones

- dev-client/src/components/StaticMapView.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
Please check this looks good in iOS emulator before merging!
Fixes #764 
Icons should look reasonably sized on both platforms.
> fix: remove map icon size workaround, fixed upstream

- dev-client/src/translations/en.json
Update the text on the projects tab when the list of projects is empty
One fix for #754
> fix: update empty project text

- dev-client/src/translations/en.json
Changing the text of the confirmation dialog for deleting notes
One fix for #750
> fix: changing confirmation message for deleting notes

- dev-client/ios/Podfile.lock
- dev-client/ios/Terraso LandPKS/Info.plist
- dev-client/src/screens/SlopeScreen/SlopeMeterScreen.tsx
- dev-client/src/translations/en.json
george boole, how you vex me so
Fixes camera permissions prompt for the slope meter screen. @paulschreiber can you check if this works on your iOS device before merging?
Fixes #765 
Slope screen should show a button saying "grant camera permissions" when camera permissions have not been granted, and then show the camera when they have been. Camera should disappear again if permissions are revoked.
> fix: camera permissions prompt

- dev-client/src/screens/SiteScreen/SiteScreen.tsx
Fixes the `"" is not a valid dimension. Dimensions must be a number, "auto" (...)` warning.
Fixes #....
> fix: make the 'not a valid dimension' native-base warning go away

- dev-client/src/theme.ts
Use valid justifyContent value in theme.ts. Avoids warning.
> fix: use valid justifyContent value in theme.ts

- dev-client/src/screens/SiteScreen/SiteScreen.tsx
Avoid null deref of coords on site screen.
> fix: avoid null deref of coords

- dev-client/ios/Terraso LandPKS/Info.plist
Add UIRequiresFullScreen to Info.plist. We hope this wll help with locking to landscape orientation on iOS.
> chore: add UIRequiresFullScreen to Info.plist

- dev-client/src/translations/en.json
Change "Pinned Site Note" to "Pinned Note"
One fix for #756
> fix: update pinned note label

- dev-client/Gemfile
- dev-client/Gemfile.lock
Update CocoaPods to 1.15.2+. 1.15.0/1.15.1 were broken.
> chore: update CocoaPods to 1.15.2+

- dev-client/src/screens/SiteNotesScreen/SiteNotesScreen.tsx
Removes the "Add Note" button from viewers.
Fixes #711
> fix: Restrict viewers from adding notes to sites

- dev-client/src/translations/en.json
Changing 1-15% to 2-5%, as pointed out on a demo 
No formal issue filed, it was pointed out in the weekly BLM meeting just now
> fix: slope-class-names

- dev-client/src/translations/en.json
Update label on the site filter screen from "sort projects by" to "sort sites by".
Fixes #751 
Open the site search dialog. Verify that the affected label now shows 'site' instead of 'project.'
> fix: change site search filter label text to correct term

- dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Fix first paragraph with corrected styling (bold text, not a heading) and proper punctuation. Also fix link type (remove external-link icon) and style font weight.
Fixes #917 
Open an account with an empty project screen and confirm the changes appear as expected.
> fix: update empty-project text and styling

- .github/workflows/build-shared-android.yml
Use filippoLeporati93/android-release-signer action — @r0adkll/sign-android-release has been abandoned.
> chore: use filippoLeporati93/android-release-signer action

- README.md
Only need to define the `MAPBOX_DOWNLOADS_TOKEN` in one step with the expo prebuild changes, forgot to update the README.
> docs: update docs for new mapbox secret key workflow

- .github/workflows/build-shared-android.yml
- .github/workflows/build-shared-ios.yml
- dev-client/package.json
* Get sentry project and org from environment
* cache `android` and `ios` folders
Fixes #969.
> fix: Update GitHub CI build caching

- dev-client/package-lock.json
- dev-client/package.json
update react-native-gesture-handler to 2.16.0.
> build: update react-native-gesture-handler to 2.16.0

- dev-client/src/screens/CreateProjectScreen/components/Form.tsx
Increases font the size of the project description text field.
This will address #957.
> fix: increase project description font size

- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
Use the same color for info and help icons on create site form.
This will address #916.
> fix: use same color for info and help icons on create site form

- dev-client/src/navigation/constants.ts
- dev-client/src/navigation/hooks/useNavigation.ts
- dev-client/src/navigation/navigators/LocationDashboardTabNavigator.tsx
- dev-client/src/navigation/navigators/RootNavigator.tsx
- dev-client/src/navigation/screenDefinitions.tsx
- dev-client/src/navigation/types.ts
- dev-client/src/navigation/utils/utils.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisHomeScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorCropReferenceScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorCropSoilScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/components/ColorCropScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/navigation/navigation.ts
- dev-client/src/screens/SoilScreen/ColorScreen/ColorGuideScreen.tsx
- dev-client/src/translations/en.json
Reorganizes the soil color analysis screens into a subnavigator for better state management. Now when you enter the crop screen, it re-uses the previous crop. And when leaving a crop screen, you go back to the previous crop screen if there was one, which will re-use the previous crop. 
Progress on #974
> feat: improve soil color UX

- dev-client/app.config.ts
Add ACTIVITY_RECOGNITION to blocked permissions. Expo is adding this and we don't need it.
Avoids Play Store request for additional details.
> fix: add ACTIVITY_RECOGNITION to blocked permissions

- dev-client/src/components/Icons.tsx
Increase size of tooltip icon (help) to md to match info icon.
Fixes #916.
> fix: increase size of tooltip icon to md to match info icon

- dev-client/src/screens/HomeScreen/HomeScreen.tsx
- dev-client/src/screens/HomeScreen/HomeScreenCallout.ts
- dev-client/src/screens/HomeScreen/HomeScreenCallout.tsx
- dev-client/src/screens/HomeScreen/components/SiteClusterCalloutListItem.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
- dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx
- dev-client/src/screens/HomeScreen/utils/homeScreenFilters.ts
If the user's current callout selection is excluded by their site filters, the app gracefully hides the callout rather than crashing. To enable this fix, add helper functions to the home screen's callout system to make initializing state more concise and mapping state to logic more consistent, and further refactor SiteMapCallout for general clarity.
This PR will fix the three below tickets, but several other bugs are also fixed (similar issues would have affected site clusters and filtering.) The general problem was that components which rendered based on the callout state were not written to consider that the selected callout site(s) might be excluded by the filter.
Also do some general incremental cleanup to the Home screen for readability and clarity: relocate filters and callout state …
> fix: Fix bad assumptions in Home screen callout selection and refactor for clarity.

- dev-client/app.config.ts
Enable push notification entitlement.
Fixes this warning (in emails from Apple):
>ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the 'aps-environment' entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the 'aps-environment' entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or …
> fix: restore push notification entitlement

- dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx
- dev-client/src/screens/ProjectTeamScreen/components/UserInfo.tsx
- dev-client/src/screens/ProjectTeamScreen/components/UserItem.tsx
- dev-client/src/screens/ProjectTeamScreen/components/UserList.tsx
- dev-client/src/translations/en.json
Hide the "leave project" button on the project team view if the user in question is the only manager for the project. Also refactor the associated components for clarity.
Fixes #[496](https://github.com/techmatters/terraso-mobile-client/issues/496)
Create a project and invite a single collaborator. Observe that the option to leave the project is not available. Change the collaborator's role and observe that the option is now available. Change the role back and observe that the option is no longer available.
> fix: prevent the removal of the only manager from projects

- .github/workflows/test.yml
- CONTRIBUTING.md
- dev-client/__tests__/integration/CreateProjectScreen-test.tsx
- dev-client/__tests__/integration/CreateSiteScreen-test.tsx
- dev-client/__tests__/integration/LocationDashboardScreen-test.tsx
- dev-client/__tests__/integration/LoginScreen-test.tsx
- dev-client/__tests__/integration/ProjectViewScreen-test.tsx
- dev-client/__tests__/integration/SlopeScreen-test.tsx
- dev-client/__tests__/integration/SoilScreen-test.tsx
- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/LoginScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/SlopeScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/babel.config.js
- dev-client/jest/data.ts
- dev-client/jest/setup.ts
- dev-client/jest/utils.tsx
- dev-client/package-lock.json
- dev-client/package.json
Adds a number of snapshot tests of screens, and sets them up to run in CI. I'd appreciate feedback from people if this is mergeable as is, and then can be iterated on in further PRs, or if we'd like to see more progress before merging this.
Basically what's happened here is I've set up a render hook which can accept an initial state for the redux store and a route name, and found a way to get the house of cards of jest mocks for our dependencies to produce reasonable snapshot results. I then fudged around with the implementation files to confirm the snapshots also fudge in the same way. There's many many dimensions for future improvement (testing more screens, testing screens for different sets of data loaded, interacting with screens, coverage statistics, etc) but I wanted to check in if …
> feat: snapshot integration testing!

- dev-client/src/screens/HomeScreen/components/TemporarySiteCallout.tsx
Remove precipitation average from location popover.
Addresses #1207.
> fix: remove precipitation average from location popover

- dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx
- dev-client/src/screens/SiteNotesScreen/components/SiteInstructionsCard.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/PhotoConditions.tsx
- dev-client/src/screens/SoilScreen/TextureScreen.tsx
- dev-client/src/screens/SoilScreen/components/RenderValues.tsx
- dev-client/src/screens/Toasts.tsx
- dev-client/src/translations/en.json
Use snake_case for additional i18n keys. Left in place for now, as these likely require code changes:
* sorting-related keys (*Asc, *Desc)
* soil.collection_method subkeys and soil.data subkeys
> fix: use snake_case for additional i18n keys

- dev-client/src/navigation/navigators/BottomNavigator.tsx
- dev-client/src/translations/en.json
Remove the logout button from the bottom navigator, as it is being replaced with the settings screen in https://github.com/techmatters/terraso-mobile-client/pull/1235. Change the 'home' navigation option to 'sites'. Note that the sites screen is still internally called the 'home' screen; I decided that this was too heavyweight of a refactor to handle in this PR. (Issue #1236 has been created to handle this cleanup when we have capacity).
Fixes #1224 
Open application and verify contents of bottom navigator.
> feat: remove logout from bottom nav, rename home to sites

- dev-client/__tests__/context/GeospatialContext.test.tsx
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/jest/data.ts
- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/components/util/site.ts
- dev-client/src/screens/HomeScreen/components/TemporarySiteCallout.tsx
- dev-client/src/screens/SiteScreen/SiteScreen.tsx
- dev-client/src/services.ts
- dev-client/src/translations/en.json
Add elevation to temporary site callout. 
- Show spinner when it is loading.
- Show unknown on failure.
- Uses nationalmap.gov API
> feat: add elevation to temporary site callout

- dev-client/src/components/ChipBadge.tsx
- dev-client/src/components/SiteBadge.tsx
- dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
- dev-client/src/screens/ProjectListScreen/components/ProjectPreviewCard.tsx
Remove help button and "learn more" link from Projects screen.
Addresses #1268.
> fix: Remove help button and "learn more" link from Projects screen

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/components/StaticMapView.tsx
- dev-client/src/context/GeospatialContext.tsx
- dev-client/src/model/map/mapSlice.ts
- dev-client/src/screens/CreateSiteScreen/CreateSiteScreen.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx
- dev-client/src/screens/HomeScreen/HomeScreen.tsx
- dev-client/src/screens/HomeScreen/HomeScreenCallout.ts
- dev-client/src/screens/HomeScreen/components/MapSearch.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
- dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx
- dev-client/src/screens/HomeScreen/components/TemporarySiteCallout.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardScreen.tsx
- dev-client/src/screens/LocationScreens/LocationSoilIdScreen.tsx
- dev-client/src/screens/LocationScreens/components/CreateSiteButton.tsx
Updates the client-shared version to expose the new soil id service.
Also fixes a type error, and consolidates the `Coords` type with the new one that was needed upstream.
Resolves https://github.com/techmatters/terraso-backend/issues/1265
Resolves https://github.com/techmatters/terraso-backend/issues/1266
> feat: update client shared with soil id service

- dev-client/src/components/SoilPropertiesDataTable.tsx
- dev-client/src/components/util/nativeBaseAdapters.ts
- dev-client/src/navigation/navigators/LocationDashboardTabNavigator.tsx
- dev-client/src/screens/LocationScreens/LocationSoilIdScreen.tsx
- dev-client/src/screens/LocationScreens/components/SiteDataSection.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Add soil properties table (with bogus data) 
Add "Add soil data >" button (but does not yet navigate to the correct tab)
Partially implements #1230 
Would like reviews on this part now, to unblock Ruxandra's work that uses the table
Look at the bottom of the Soil ID sheet for a site
Currently looks like this: 
(alas, I was trying so hard to get the table narrow enough to not need horizontal scrolling, but still fit the strings nicely *shakes fist at Android*)
> feat: Add "Soil Properties" content with table using bogus data + unfinished "Add soil data" button

- dev-client/src/components/SoilPropertiesDataTable.tsx
- dev-client/src/model/soilId/soilIdPlaceholders.ts
- dev-client/src/screens/LocationScreens/components/SiteDataSection.tsx
- dev-client/src/screens/LocationScreens/components/SoilIdSections.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/PropertiesDisplay.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/PropertiesScoreDisplay.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/SiteScoreInfoContent.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/TempScoreInfoContent.tsx
- dev-client/src/translations/en.json
Add soil data table to temp location and site soil info sheets. Refactor some associated components and add basic data plumbing to make future integration work on soil ID easier.
Fixes [#....](https://github.com/techmatters/terraso-mobile-client/issues/1158)
Open temp location pin and navigate to info sheet. Verify that table displays as expected. Open a site and navigate to the info sheet. Verify that the table displays as expected there as well.
> feat: integrate soil id info sheets with data table

- dev-client/src/navigation/navigators/SiteLocationDashboardTabNavigator.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardScreen.tsx
- dev-client/src/screens/LocationScreens/LocationSoilIdScreen.tsx
- dev-client/src/screens/LocationScreens/components/SiteDataSection.tsx
- Button to “Add soil data” navigates to the site’s “Soil” tab
- Button does not appear for Viewer role
- Minor renaming
2nd PR implementing #1230 
1. Go to a site's soil ID screen and see the "Add soil data" button (unless you're only a Viewer of the site).
2. Click it and confirm it goes to the Soil tab for the site
> Feat: 'Add soil data' button navigates to site's soil data tab

- dev-client/src/components/tables/soilProperties/SoilPropertiesData.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SiteSoilPropertiesDataSection.tsx
- Create table rows with real soilData collected for the site
- Use `SoilData.depthIntervals` (which has one per depth interval, regardless of if there are data collected for that interval) to make table rows, instead of `SoilData.depthDependentData` (which excludes depth intervals for which there are no data). 
Implements #1231
> feat: Use actual site data for the soil properties table

- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
Don't crash when deleting a site
- don't navigate to site dashboard or project screen via pop()
- avoid null deference on site settings screen
Addresses #861.
> fix: don't crash after deleting site

- dev-client/src/translations/en.json
On the projects > add team member screen, update the string to match implementation (allow single email address, not multiple).
Request to support multiple email addresses: #731
> fix: update string to match implementation (allow single email address)

- dev-client/src/components/StaticMapView.tsx
- dev-client/src/screens/HomeScreen/HomeScreenCallout.ts
- dev-client/src/screens/HomeScreen/components/LatLngDetail.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
- dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx
- dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx
- dev-client/src/screens/HomeScreen/components/TemporarySiteCallout.tsx
- dev-client/src/services.ts
- dev-client/src/translations/en.json
- dev-client/src/util.ts
Add lat/lng to temporary site popover.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/720
> feat: add lat/lng to temporary site popover

- dev-client/app.config.ts
Add APP_VERSION to ENV_CONFIG. Allows version to render correctly in settings screen.
Addresses #1286.
> fix: add APP_VERSION to ENV_CONFIG

- dev-client/src/auth/index.ts
- dev-client/src/screens/LoginScreen.tsx
Don’t sent client_id for google/ms SSO. Re-enables login for non-Apple providers.
> fix: don’t sent client_id for google/ms SSO

- dev-client/src/components/tables/soilProperties/SoilPropertiesDataTable.tsx
- dev-client/src/translations/en.json
Fixes incorrect "data source" label text and expands width of table columns per feedback on #1156 and #1158.
Open application and navigated to soil info sheets. Verify that label is fixed and columns (other than Texture) are wide enough for their content.
> fix: text and table width for soil info sheets

- dev-client/src/screens/HomeScreen/components/SiteListBottomSheet.tsx
Set max height of bottom sheet to 75%. Set default height to 50%, whether or not sites are present.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1485 and https://github.com/techmatters/terraso-mobile-client/issues/1483
> fix: set max height of bottom sheet to 75% and default height to 50%

- dev-client/__tests__/integration/__snapshots__/SlopeScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/src/components/sheets/OverlaySheet.tsx
- dev-client/src/components/tables/soilProperties/SoilPropertiesDataTable.tsx
Due to an oversight in implementation, `SoilPropertiesDataTable` and `OverlaySheet` did not scroll correctly when used together. Apply a fix from the`gorhom` sheet documentation (https://ui.gorhom.dev/components/bottom-sheet/troubleshooting/#adding-horizontal-flatlist-or-scrollview-is-not-working-properly-on-android) and use a suitable configuration of `ScrollView` and the `gorhom` properties.
Fixes #1397
- Open soil ID info sheets. Verify that both table and sheet can scroll.
- Open location dashboard screen. Verify that both table and screen can scroll.
> fix: make OverlaySheet and SoilPropertiesDataTable correctly interact

- dev-client/src/screens/HomeScreen/components/SiteListBottomSheet.tsx
- dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx
- dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
Use react-native-paper spinner instead of NativeBase.
Part of https://github.com/techmatters/terraso-product/issues/742.
> fix: use react-native-paper spinner instead of NativeBase

- dev-client/src/components/tables/soilProperties/SoilPropertiesDataTable.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SiteSlopeDataSection.tsx
- dev-client/src/translations/en.json
- Put steepness number inside box if steepness is represented by a number, not an image
- "Add slope" button goes to Slope Steepness screen instead of general Slope screen 
- "Slope" title changes to "Slope Steepness"
- If there are no depth intervals for a site, show a single empty row in the soil properties data table 
This is follow-up work for #1200, #1230
> Fix: Minor UX updates to site data section on soil id screen 

- dev-client/src/model/soilId/soilIdRanking.ts
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SoilIdMatchesSection.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SoilMatchTile.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/ScoreTile.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Soil ID page for a site and a temporary location should show tiles with match percentage and soil name.
NOTE: This builds off the feat/soil-id-data branch that is not yet submitted. Please let me know if there's a standard workflow for this.
Implements #1197
> Feat: Create soil match tiles using data from soil id API

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/App.tsx
- dev-client/src/navigation/navigators/SiteLocationDashboardTabNavigator.tsx
- dev-client/src/screens/CreateProjectScreen/CreateProjectScreen.tsx
- dev-client/src/screens/CreateSiteScreen/CreateSiteScreen.tsx
- dev-client/src/screens/LocationScreens/LocationSoilIdScreen.tsx
- dev-client/src/screens/ProjectViewScreen.tsx
- dev-client/src/screens/ScreenScaffold.tsx
- dev-client/src/screens/SlopeScreen/SlopeMeterScreen.tsx
Fixes crash issues with info overlay sheets opening on certain screens.
This was inadvertently introduced by #1397, which enabled the Gorhom Bottom Sheet Modal's nested scrolling; however, this also introduced a dependency on having a navigation context available. Because our bottom sheet providers were not consistently placed in the application hierarchy, certain screens did not have access to the context, which caused the crash. This fix standardizes their provisioning to occur within the `ScreenScaffold` component and ensure that all bottom sheets exist within it. Incidentally, this also fixes issues with sheets opening to unexpected heights, which was another side-effect of the inconsistent placement of the `Provider` component.
Fixes #1533
Visit all screens featuring info overlay …
> fix: info overlay sheet crashes

- dev-client/src/screens/LocationScreens/components/soilId/SoilMatchTile.tsx
For some reason the fonts on iOS and Android are different, such that 74px was not sufficient to fit "100%" without wrapping. Just up the width of that section slightly for now, and hopefully [#1537](https://github.com/techmatters/terraso-mobile-client/issues/1537) will more holistically address the issue.
Follow-up work to #1197
> fix: make 100% fit on one line in SoilMatchTile on iOS

- dev-client/src/App.tsx
- dev-client/src/screens/ScreenScaffold.tsx
Fix crashes in filter screens that use overlay sheet selection components by reintroducing the root-level `BottomSheetModalProvider`. Add another `BottomSheetModalProvider` underneath the `NativeBaseProvider` so that other components can still render under floating NativeBase elements, fixing the unexpected FAB issue.
Fixes #1536
Open filter modals and verify that filter selections work as expected. Open site color entry screen and verify that "Done" button no longer floats above info modal.
> fix: reinstate overlay sheet providers in app stack to fix crashes and conflict w/ FAB

- dev-client/src/App.tsx
- dev-client/src/constants.ts
- dev-client/src/context/HomeScreenContext.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx
- dev-client/src/screens/HomeScreen/HomeScreen.tsx
- dev-client/src/screens/HomeScreen/components/MapSearch.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
- dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx
The bottom sheet now hides when:
- you tap on the map and get a temporary location callout ([1482](https://github.com/techmatters/terraso-mobile-client/issues/1482))
- you tap on the pin icon in the site list to bring up a site callout
- you start searching the map (this is better experience than what is suggested in [871](https://github.com/techmatters/terraso-mobile-client/issues/871))
- move HomeScreenContext to its own component
See also https://github.com/techmatters/terraso-mobile-client/issues/753
> fix: hide bottom sheet when interacting with map

- dev-client/src/components/ListFilter.tsx
- dev-client/src/screens/HomeScreen/components/MapSearch.tsx
- dev-client/src/screens/HomeScreen/components/SiteMap.tsx
On home screen hide keyboard when tapping on map (after searching for places) or tapping on search filter icon in sites list.
> fix: on home screen, hide keyboard when interacting with map or search filter

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/src/components/IntervalForm.tsx
- dev-client/src/components/ListFilter.tsx
- dev-client/src/components/SiteNoteForm.tsx
- dev-client/src/components/form/FormInput.tsx
- dev-client/src/components/form/FormSwitch.tsx
- dev-client/src/components/inputs/Select.tsx
- dev-client/src/components/inputs/Text.tsx
- dev-client/src/components/inputs/TextInput.tsx
- dev-client/src/screens/AddUserToProjectScreen/components/FreeformTextInput.tsx
- dev-client/src/screens/CreateProjectScreen/components/CreateProjectForm.tsx
- dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
- dev-client/src/screens/HomeScreen/components/MapSearch.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
- dev-client/src/screens/ProjectInputScreen/RequiredDataSettings.tsx
- dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
- dev-client/src/screens/ProjectSettingsScreen.tsx
- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/screens/SiteTransferProjectScreen/components/CheckboxGroup.tsx
- dev-client/src/screens/SiteTransferProjectScreen/components/ListHeader.tsx
- dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx
- dev-client/src/screens/SoilScreen/components/EditIntervalModal.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Redo the text and search components based on React Native Paper
- remove old SearchBar and FormTextArea components
- create new TextInputComponent
- eliminates our own code for adding search icons and clearing searches
- remove some duplicate string entries for project name/description/search
- refactored the ProjectForm code to get rid of SharedFormComponents (which wasn't shared) and EditHeader (which never appeared)
- use consistent spacing on lists of checkboxes and switches
- remove nonfunctional download link from project settings
Courtney approved the use of the rounded corner search field.
Corresponding Select box fix https://github.com/techmatters/terraso-mobile-client/pull/1443
Addresses https://github.com/techmatters/terraso-mobile-client/issues/688.
> fix: redo the text and search components based on React Native Paper

- dev-client/src/components/RadioBlock.tsx
- dev-client/src/screens/AddUserToProjectScreen/components/MinimalUserDisplay.tsx
- dev-client/src/screens/ManageTeamMemberScreen.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
Gets closer to the Figma design for the "Manage Team Member" screen ([link](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-12866&m=dev)). 
This includes some work to set up for [#1505](https://github.com/techmatters/terraso-mobile-client/issues/1505)/[#1447](https://github.com/techmatters/terraso-mobile-client/issues/1447). But also some screen-specific styling updates cuz I was already there 
Includes: 
- Add title
- Include user photo (and make smaller to match spec)
- Reorder and slightly restyle radio button text
- Minor spacing changes
Changes still needed for the screen to be up-to-spec:
- Put the Save button in exactly the right place (seems like a bigger thing to address holistically)
- Fix "Remove from project" button …
> feat: Update design for ManageTeamMemberScreen

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/screens/ScreenScaffold.tsx
Remove the extra space below bottom sheet on iOS devices with notches/islands.
Before:
After:
> fix: remove extra space below sheet on iOS devices with notches/islands

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/src/components/AddIntervalModal.tsx
- dev-client/src/components/IntervalForm.tsx
- dev-client/src/components/ScreenFormWrapper.tsx
- dev-client/src/constants.ts
- dev-client/src/schemas/intervalSchema.ts
- dev-client/src/schemas/siteValidationSchema.ts
- dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectScreen.tsx
- dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/ColorScreen.tsx
- dev-client/src/screens/SoilScreen/SoilScreen.tsx
- dev-client/src/screens/SoilScreen/TextureScreen.tsx
- dev-client/src/screens/SoilScreen/components/EditIntervalModal.tsx
- dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
- dev-client/src/translations/en.json
Text input field improvements:
- add text labels to add team member, custom soil depth interval, slope steepness screens
- don’t prompt to delete new, blank notes
- on site creation form, reduce space above GPS accuracy label
- add project description minimum length
- enforce max length for site name, project name and project description
- ensure depth intervals are integers
- add header to "add depth interval" screen (and fix layout spacing)
Alsos:
- move done button to bottom right on color and soil surface screens
> fix: text input field improvements

- dev-client/src/components/buttons/list/ListButton.tsx
- dev-client/src/components/modals/SignOutModal.tsx
- dev-client/src/hooks/userDeletionRequest.ts
- dev-client/src/screens/DeleteAccountScreen/DeleteAccountScreen.tsx
- dev-client/src/screens/DeleteAccountScreen/components/DeleteAccountConfirmForm.tsx
- dev-client/src/screens/UserSettingsScreen/UserSettingsScreen.tsx
- dev-client/src/screens/UserSettingsScreen/components/actions/DeleteAccountButton.tsx
- dev-client/src/screens/UserSettingsScreen/components/actions/SignOutButton.tsx
- dev-client/src/translations/en.json
Update the delete account workflow to disable buttons when the deletion is pending, simplifying the hook's internals to remove unnecessary state tracking. Do some associated refactoring to make deletion / logout systems more consistently implemented.
#1179
Open the user settings screen and execute the delete account workflow. Observe that the action button does not allow the user to click it again while the request is pending. Observe that the button on the settings screen is now disabled and shows the "Pending" sub-label.
> feat: delete account pending buttons

- dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
Create sites at location indicated on map (not current location) (bug introduced in v138)
Use formatCoordinate on site creation for and site dashboard.
Fixes #1559.
> fix: create sites at location indicated on map (not current location)

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/components/ScreenFormWrapper.tsx
- dev-client/src/components/icons/HorizontalIconButton.tsx
- dev-client/src/components/icons/IconLink.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
- dev-client/src/screens/ProjectSettingsScreen.tsx
- dev-client/src/screens/SiteNotesScreen/SiteNotesScreen.tsx
- dev-client/src/screens/SiteNotesScreen/components/SiteInstructionsCard.tsx
- dev-client/src/screens/SiteNotesScreen/components/SiteNoteCard.tsx
- dev-client/src/translations/en.json
- dev-client/src/util.ts
Update site notes screens to match designs
- use pushpin icon
- use date and time (not just date)
- change note titles
- fix button color
- fix size and position of delete button
Also fixed:
- project settings screen is full height
- fix size and position of delete project icon/link
Addresses https://github.com/techmatters/terraso-mobile-client/issues/750
> fix: update site notes screens to match designs

- dev-client/src/navigation/components/ScreenBackButton.tsx
- dev-client/src/theme.ts
Use correct color for pressed state of buttons (dark green by default)
- Manually set pressed state color for IconButton
- Manually set pressed state color for ScreenBackButton
- Manually set pressed state color for ListButton
> fix: use correct color for pressed state of buttons

- dev-client/src/screens/DeleteAccountScreen/components/DeleteAccountConfirmContent.tsx
Reorder elements in deletion screen to adjust spacing, per design request.
Feedback on #1263
Open deletion screen and verify that there is less spacing between the bullet-point section and the paragraph below.
> fix: spacing on deletion screen text per design request

- dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx
- dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardScreen.tsx
Pass elevation data through to Learn More screen when creating sites via map callout.
Part of fix for https://github.com/techmatters/terraso-product/issues/774
> fix: pass elevation data through to Learn More screen

- dev-client/src/screens/LocationScreens/components/soilId/SoilMatchTile.tsx
To prevent 100% match score from wrapping on some devices with default font size
Don't love this as a solution, but couldn't come up with something quick and better. Talked with Courtney and we figured we'd just try this for now.
Also remove styling that is already specified via the Text variant
Addresses comments of [#1197](https://github.com/techmatters/terraso-mobile-client/issues/1197)
> fix: Slightly increase width of soil match tile score 

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/navigation/screenDefinitions.tsx
- dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectRoleScreen.tsx
- dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectScreen.tsx
- dev-client/src/screens/AddUserToProjectScreen/components/AddTeamMemberForm.tsx
- dev-client/src/screens/AddUserToProjectScreen/components/MinimalUserDisplay.tsx
- dev-client/src/screens/AddUserToProjectScreen/components/ProjectRoleRadioBlock.tsx
- dev-client/src/translations/en.json
From acceptance criteria of #1447:
- 1st "Add Team Member" screen:
- Update design upon first opening the screen 
- Use new up-to-spec TextInput component
- Red text "Required" shows up when nothing there (do we want this?)
- Red text shows up when email is invalid email
- Next button is disabled until email address has a valid email format entry
- Next button triggers backend validation and shows error message if email is not a terraso user or already in the project
- Next button goes to the 2nd screen if email is a terraso user who's not already in the project
- User can't get to this screen unless they're a Manager role
- 2nd "Add Team Member" screen (to choose role):
- Looks very similar to "Manage Team Member" screen
- Back arrow in app bar goes back to 1st "Add Team Member" screen, …
> feat: Implement new "Add team member" flow

- dev-client/src/screens/ManageTeamMemberScreen.tsx
Still not exactly consistent / unified with all the other buttons of its type, but at least looks like the spec for Capri
Sorta mentioned in #1447, though it's pretty tangential honestly
Before: 
After:
> fix: Restyle 'Remove from project' button on Manage Team Member screen

- dev-client/src/hooks/userDeletionRequest.ts
Avoid null dereference that crashed the app when signing out.
> fix: don’t crash on sign out

- .github/workflows/build-shared-android.yml
- .github/workflows/build-shared-ios.yml
- dev-client/app.config.ts
When building for iOS and Android, get SENTRY_ORG and SENTRY_PROJECT from vars instead of inputs.
> fix: get SENTRY_ORG and SENTRY_PROJECT from vars instead of inputs

- dev-client/src/screens/ProjectInputScreen/RequiredDataSettings.tsx
Avoid warnings on missing i18n keys. This was done in https://github.com/techmatters/terraso-mobile-client/pull/1508 but got lost.
> fix: avoid warnings on missing i18n keys

- dev-client/src/screens/ProjectSitesScreen.tsx
Correct behavior of site card menu on project management screen
- remove dot beside "delete site" menu item
- don't block dialog with menu (Android)
- don't crash (iOS)
Use React Native Paper instead of NativeBase.
Addresses #1592.
> fix: correct behavior of site card menu on project management screen

- dev-client/src/translations/en.json
Make URL on privacy sheet match request from design. Note that the URL itself is not yet valid on the terraso.org site, but this will be its location at launch.
Fixes #755
Open privacy sheet and verify that expected URL is opened from portal link.
> fix: url for landpks data portal

- dev-client/src/components/ProjectSelect.tsx
- dev-client/src/hooks/permissionHooks.ts
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
Add a hook allowing us to filter projects based on the current user's role for the project, and use it in `ProjectSelect` and `CreateSiteForm` so that users aren't able to create sites for projects to which they cannot add.
#944
Create a new site and verify that projects for which the current user is a viewer are not included in the select list, while projects for which the user is a manager or contributor are included.
> fix: filter projects by role for site transfer selection

- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
fix spacing/margins on soil id tile:
Addresses #1652.
> fix: fix spacing/margins on soil id tile

- dev-client/src/screens/SiteNotesScreen/components/SiteNoteCard.tsx
Per design feedback on #709, increase size of site note edit icon, change card press behavior to only open edit screen, and remove truncation from site notes (it still exists for pinned notes).
#709
Verify that tapping on a site note without edit permissions does nothing. Verify that multiline site notes are no longer truncated after 3 lines.
> fix: site notes usability

- dev-client/.depcheckrc
- dev-client/src/components/inputs/image/ImagePicker.tsx
- dev-client/src/components/inputs/image/PickImageButton.tsx
- dev-client/src/components/modals/PermissionsRequestModal.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisHomeScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/components/ColorCropScreen.tsx
- dev-client/src/screens/SlopeScreen/SlopeMeterScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/ColorGuideScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/CameraWorkflow.tsx
- dev-client/src/translations/en.json
What it says on the tin. In draft til I can validate on iOS. Right now when you fix the permissions in settings from the slope screen and then return to the app, you need to leave/re-enter the slope screen to get the app to pick up on the change, the `usePermissions` hook doesn't seem to re-render the screen. not sure if there's a better workaround.
Fixes https://github.com/techmatters/terraso-mobile-client/issues/1328
> fix: request permissions before using camera/media library in image picker

- dev-client/src/screens/LocationScreens/components/soilId/SoilMatchTile.tsx
- dev-client/src/theme.ts
Another attempt at preventing the "100%" from wrapping (or truncating) -- this time by decreasing the font size and using adjustsfontSizeToFit onto one line.
Addresses #1635 
However, I still don't understand why:
a) With 30px or 32px font size, we'd get "100" without the "%" sign, even with adjustsFontSizeToFit?
b) Why font size and Box width are both specified in fixed pixels but not 
Before --> After:
And also any individual percentage, like the "100%", will get smaller if it would overflow its box, like this (but note this is not the new 24px font size):
> fix: Decrease font size of soil match percent, use adjustsFontSizeToFit

- dev-client/src/screens/LocationScreens/components/soilInfo/ScoreInfoContainer.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/TempScoreInfoContent.tsx
Pressing the "Create Site Here" button would not close the soil info overlay sheet that it was on (though it would navigate to a different sheet underneath the open overlay sheet). This was undesirable. If we wanted to fix it, we could probably pass the button a ref to the overlay sheet to allow the button to close the overlay sheet on press, but Courtney suggested just removing the button. I think this makes sense because the soil info sheet is just specific to that soil, and if you want to create a site from that temporary location, you can just close the overlay sheet to access another "Create Site Here" button.
Also added a bit of margin at the bottom to let it breathe and not feel like the content is so close to the edge of the screen.
Fixes …
> fix: Remove 'Create Site Here' button on overlay sheet, add bottom margin

- dev-client/src/components/links/ExternalLink.tsx
- dev-client/src/components/links/InternalLink.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/SoilInfoDisplay.tsx
- dev-client/src/util.ts
Validate information URLs returned by the soil ID algorithm before displaying them to the user.
#1715
Verify that soil ID results that previously crashed now have their URL components hidden.
> fix: validate soil id urls before allowing users to navigate to them

- .github/ISSUE_TEMPLATE/mobile_bug_report.yml
auto add labels to bug reports
Add labels "bug", and "needs triage" to issues filed with this formed. 
- got sample code [from this conversation](https://github.com/orgs/community/discussions/23682#discussioncomment-3241404)
> fix: Update mobile_bug_report.yml to auto-add labels

- dev-client/src/model/elevation/elevationFunctions.ts
Per request from @paulschreiber, use a constant in the elevation cache rather than hardcoded 5 decimal places.
> refactor: use coordinate precision constant

- dev-client/src/App.tsx
- dev-client/src/components/sheets/OverlaySheet.tsx
- dev-client/src/context/HeaderHeightContext.tsx
- dev-client/src/screens/HomeScreen/components/LandPKSInfoModal.tsx
- dev-client/src/screens/ScreenScaffold.tsx
We had issues with nested overlay sheets opening to inconsistent heights, which in turn made their close buttons inaccessible. This was because the `HeaderHeight` context that tells them their opening limit is scoped to the `ScreenScaffold` component, which is context that nested sheets do not have (since they are opening in the `BottomSheetModalProvider` outside of the scaffold). This fixes the issue by making `HeaderHeight` context available to the entire app, with `ScreenScaffold` just setting the current value as a side effect.
#1651
Open info overlay sheets, including the nested ones in Soil ID, and verify that all open to the expected height and can be closed on both IOS and Android.
> fix: make header height context available to all overlay sheets

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/screens/SoilScreen/components/DepthEditor.tsx
- dev-client/src/screens/SoilScreen/components/SoilDepthSummary.tsx
Update client-shared dependency to include fix for warning.
Fixes #1322
See client-shared PR (https://github.com/techmatters/terraso-client-shared/pull/733)
> fix: soil selector warning

- dev-client/__tests__/integration/SlopeScreen-test.tsx
- dev-client/__tests__/integration/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/screens/SoilScreen/components/EditSiteSoilDepthPreset.tsx
- dev-client/src/translations/en.json
For depth presets:
- remove LandPKS
- add BLM monitoring standard
- make NRCS the default, and change user-visible string to "NRCS/GSP"
mobile-client part to address [#1541](https://github.com/techmatters/terraso-mobile-client/issues/1541)
> feat: Update depth presets for Capri

- dev-client/src/translations/en.json
Update home screen name so app bar shows "LandPKS Soil ID."
> fix: update home screen name so app bar shows LandPKS Soil ID

- dev-client/__tests__/integration/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/integration/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/components/links/InternalLink.tsx
- dev-client/src/theme.ts
Reimplement `InternalLink` to be compliant with spec, discarding old `NativeBase` `Link` implementation for a pressable `Text` element. Incorporate `expo-web-browser` for embedded web view functionality.
#1332
Open sections of the application containing external links. Verify that they match the component specification. Verify that links open in an embedded browser window rather than the user's browser app.
> feat: update InternalLink to be spec compliant

- dev-client/src/model/elevation/elevationHooks.ts
- dev-client/src/model/elevation/elevationSelectors.ts
- dev-client/src/model/elevation/elevationService.ts
- dev-client/src/model/elevation/elevationSlice.ts
- dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx
Fix an oversight in elevation hook usage which did not correctly distinguish between unknown elevation and loading elevation when rendering for users. Refactor some nearby code for greater clarity.
#1787
Select a point on the map both inside and outside the US and verify that elevation values show as "unknown" when outside the US. Verify that loading indicator still functions.
> fix: correctly handle unknown elevation vs. loading

- dev-client/metro.config.js
- dev-client/src/App.tsx
Add Sentry mobile replay support.
docs:
* https://docs.sentry.io/product/explore/session-replay/mobile/
* https://github.com/getsentry/sentry-react-native/releases/tag/5.26.0
> feat: add Sentry mobile replay

- dev-client/src/components/modals/ConfirmDeleteDepthModal.tsx
- dev-client/src/components/tables/DataGridTable.tsx
- dev-client/src/screens/ProjectInputScreen/DepthTable.tsx
- dev-client/src/screens/SoilScreen/components/EditDepthModal.tsx
- add delete depth modal (same one as used for deleting depth intervals for sites)
- fix warning about needing unique 'key' prop
Addresses #1639
> Fix: add modal to confirm deleting depth interval for projects 

- dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx
- dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx
- dev-client/src/translations/en.json
On slope data screen:
- hide edit buttons from viewers
- limit percentage to a maximum of 999%
- add maxlength attributes to percentage and degree text fields
Addresses https://github.com/techmatters/terraso-mobile-client/issues/848
Not adjusting the grey color, which will be handled with text field component work.
> fix: on slope data screen, hide edit buttons from viewers and limit percentage input

- dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
- dev-client/src/screens/SiteTransferProjectScreen/components/ListHeader.tsx
- dev-client/src/translations/en.json
Remove tooltip from transfer sites screen
Add spacing below site transfer accordion with sites.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1846 and https://github.com/techmatters/terraso-mobile-client/issues/1845
> fix: remove tooltip from and fix spacing on transfer sites screen

- dev-client/metro.config.js
- dev-client/src/App.tsx
- don't mask sentry replay data in dev/staging environments
- correct annotateReactComponents configuration
> fix: don't mask sentry replay data in dev/staging environments; update annotateReactComponents config

- dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx
- dev-client/src/translations/en.json
Update name of team button to Add Team Member; ensure button width is size of text label.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1890
The button width became full width when `alignItems="flex-start"` was removed in https://github.com/techmatters/terraso-mobile-client/pull/1878/commits/bab67a8110f5d18a29dde7369ad529a95c544e30 as part of https://github.com/techmatters/terraso-mobile-client/pull/1878
> fix: update name of team button; ensure width is size of text label

- dev-client/src/navigation/navigators/RootNavigator.tsx
- dev-client/src/screens/BottomTabsScreen.tsx
App used to do location stuff in RootNavigator, resulting in asking user for location permission on the welcome screen. Now do the same stuff, but instead on the BottomTabsScreen (which would ask for permissions effectively on the home screen after login)
Relatedly: I don't think _everything_ you could do to `locationManager` implicitly launches a permissions check -- like you can do locationManager.setMinDisplacement and it doesn't -- but it seems like stuff to do with using the user's location does.
**Side note**: There is still this warning before user has given permissions (was happening from RootNavigator code, now in BottomTabsScreen because this change moves the code there), but that seems like an orthogonal concern:
Addresses #1808 
1. Uninstall and reinstall app
2. Open the app …
> fix: Ask for location permissions on home screen after login

- dev-client/src/model/elevation/elevationService.ts
Gracefully handle NationalMaps.gov "unable to process" error
Example: 
```
https://epqs.nationalmap.gov/v1/json/?x=%D9%A4%D9%A4%D9%AB%D9%A6%D9%A7%D9%A8%D9%A0%D9%A2&y=%D9%A1%D9%A4%D9%AB%D9%A2%D9%A3%D9%A8%D9%A3%D9%A1&units=Meters
```
Addresses Sentry https://techmatters.sentry.io/issues/5504862811/?
> fix: gracefully handle NationalMaps.gov "unable to process" error

- dev-client/src/components/Card.tsx
- dev-client/src/components/SiteCard.tsx
- dev-client/src/components/util/nativeBaseAdapters.ts
- dev-client/src/navigation/components/AppBar.tsx
- dev-client/src/screens/HomeScreen/components/SiteMapCallout.tsx
- dev-client/src/screens/HomeScreen/components/TemporaryLocationCallout.tsx
Wrap long site names in site card and app bar
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1656.
Before:
After:
> fix: wrap long site names in site card and app bar

- dev-client/src/screens/SiteNotesScreen/SiteNotesScreen.tsx
Make entire note view scrollable
FlatList was removed because it generated this error:
ERROR  VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
See:
https://stackoverflow.com/questions/67623952/error-virtualizedlists-should-never-be-nested-inside-plain-scrollviews-with-th
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1661
> fix: make entire note view scrollable

- dev-client/src/components/SiteCard.tsx
Wrap title on non-popover site cards.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1894
Before / After
> fix: wrap title on non-popover site cards

- dev-client/src/screens/SlopeScreen/components/ManualSteepnessModal.tsx
When clearing steepness precent or degree, clear counterpart.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/841
> fix: when clearing steepness precent or degree, clear counterpart

- dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/components/tables/DataGridTable.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
On projects screen:
* expand accordions by default
* show toggles to viewers (but disabled)
* avoid missing key warning in DataGridTable
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1850 and https://github.com/techmatters/terraso-mobile-client/issues/956
> fix: improve project inputs screen (expand accordions, show disabled toggle buttons)

- dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/components/inputs/Select.tsx
- dev-client/src/model/permissions/permissions.ts
- dev-client/src/screens/LocationScreens/LocationDashboardScreen.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SiteSlopeDataSection.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SiteSoilPropertiesDataSection.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
- dev-client/src/screens/ProjectInputScreen/SoilPitSettings.tsx
- dev-client/src/screens/ProjectSettingsScreen.tsx
- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/screens/ProjectTeamScreen/ProjectTeamScreen.tsx
- dev-client/src/screens/SiteNotesScreen/SiteNotesScreen.tsx
- dev-client/src/screens/SlopeScreen/SlopeShapeScreen.tsx
- dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/ColorScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/CameraWorkflow.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/ManualWorkflow.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/PhotoConditions.tsx
- dev-client/src/screens/SoilScreen/SoilScreen.tsx
- dev-client/src/screens/SoilScreen/TextureScreen.tsx
- dev-client/src/screens/SoilScreen/components/DepthEditor.tsx
- dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
- dev-client/src/util.ts
Remove site data entry for viewers
- for soil color, hide delete button and done button from viewers
- hide texture menu, use guide button and done button from viewers
- hide vertical cracks menu and done button from viewers
- hide slope shape done button for viewers
- disable steepness, shape and texture ImageRadio buttons for viewers
also:
- avoid key error when a single label is blank/undefined
- style disabled `<Select>` item
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1350
> fix: remove site data entry for viewers

- dev-client/__tests__/snapshot/__snapshots__/CreateProjectScreen-test.tsx.snap
- dev-client/__tests__/snapshot/__snapshots__/CreateSiteScreen-test.tsx.snap
- dev-client/__tests__/snapshot/__snapshots__/LocationDashboardScreen-test.tsx.snap
- dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/__tests__/snapshot/__snapshots__/SlopeScreen-test.tsx.snap
- dev-client/src/components/buttons/icons/IconButton.tsx
A [known bug in react native ](https://github.com/facebook/react-native/issues/13760) prevents border radius from displaying as expected in some cases on iOS. One available fix is to move the radius to a containing `View` (or equivalent) component. Apply this fix to the new `IconButton` component to fix the filled-in variants not displaying their rounded corners correctly.
Oversight in #1331
Run application in iOS and observe that icons with border or background have correct radius.
> fix: ios icon border

- dev-client/src/translations/en.json
Add missing parenthesis to delete dialog text.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/1984
> fix: add missing parenthesis to delete dialog text

- dev-client/src/model/soilId/soilIdRanking.test.tsx
- dev-client/src/model/soilId/soilIdRanking.ts
Add tests for getTopMatch and sorting, for location-based and data-based soil matches.
Note: we expect the input to come with the correct ranks (this test, as well as the product code, will not detect if a set of matches' `rank` and `score` contradict each other; it will just use `rank` and ignore `score`)
Implements #1852 
Run `npm test -- soilIdRanking.test.tsx`
> Test: Create unit tests for soil ID ranking logic

- dev-client/src/components/modals/PermissionsRequestWrapper.tsx
- dev-client/src/screens/SlopeScreen/SlopeMeterScreen.tsx
The slope meter camera was not immediately opening when the user granted permissions. I believe the issue was because the useCameraPermission hook exists separately in both the parent component (SlopeMeterScreen) and the child (PermissionsRequestWrapper). A change in the permission state for the child does not update the permission state in the parent. I’m not sure how expo's useCameraPermission is implemented, but I believe this is how React works in general. I suspect it would work when you come back to the screen because the component gets re-mounted (not just re-rendered), so the permission object would get figured out anew.
So the fix is for the SlopeMeterScreen to specify an action that happens upon granting permissions, that will update its permissions object. This is the …
> fix: Make camera permissions immediately take effect on slope meter

- dev-client/src/components/content/info/privacy/DataPrivacyContent.tsx
- dev-client/src/components/links/InternalLink.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/SoilInfoDisplay.tsx
Use ExternalLink for soil info pages. 
Also clean up external link to use a non-default export.
Addresses #1023.
> fix: use ExternalLink for soil info pages

- dev-client/src/hooks/permissionHooks.ts
- dev-client/src/model/permissions/permissions.test.ts
- dev-client/src/model/permissions/permissions.ts
Extract `userHasProjectRole` in to a function and refactor `permissionHooks` to use this function.
Add tests for `userHasProjectRole`.
Fixes #1853.
> feat: add permissions unit tests

- dev-client/locales/po/en.po
- dev-client/scripts/localization/transform-to.mjs
- dev-client/src/components/tables/soilProperties/SoilPropertiesDataTable.tsx
- dev-client/src/screens/SoilScreen/TextureScreen.tsx
- dev-client/src/screens/SoilScreen/components/RenderValues.tsx
- dev-client/src/translations/en.json
adjust strings to avoid rock_fragment.VOLUME_XX_YY being treated as plural
- change rock_fragment to rockfragment
- replace _ with : when converting to po, and replace back with : when converting to JSON
> fix: adjust strings to avoid rock_fragment.VOLUME_XX_YY being treated as plural

- dev-client/src/components/tables/soilProperties/SoilPropertiesData.tsx
- dev-client/src/model/color/colorConversions.test.tsx
- dev-client/src/model/color/colorConversions.ts
- dev-client/src/model/color/colorDetection.ts
- dev-client/src/model/color/types.ts
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisHomeScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/ColorScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/ColorDisplay.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/ManualWorkflow.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/SwitchWorkflowButton.tsx
- dev-client/src/screens/SoilScreen/components/RenderValues.tsx
Please review by commit. The first two are no-op refactors. The last commit tweaks the way we're calling the color quantization algorithm to be more robust to unexpected pixels on the edges of images. [A bug on iOS](https://github.com/techmatters/terraso-mobile-client/issues/1352) reliably produces such pixels, but we'd also like to be robust in these cases regardless in case the user gives us a sloppy croppy.
I tested this on my iphone and can no longer reproduce #1352, but if someone else could also attempt to reproduce that would bring me peace of mind.
https://github.com/techmatters/terraso-mobile-client/issues/1352
Should no longer be able to reproduce https://github.com/techmatters/terraso-mobile-client/issues/1352
> fix: ios color bug

- .github/ISSUE_TEMPLATE/mobile_bug_report.yml
Adds "Engineering" label to mobile bug template, per Derek's request [in slack](https://tech-matters.slack.com/archives/C01C1FZANBG/p1725377122948789)
> fix: add 'Engineering' label to bug template

- dev-client/src/components/modals/PermissionsRequestWrapper.tsx
- dev-client/src/screens/BottomTabsScreen.tsx
- dev-client/src/screens/HomeScreen/HomeScreen.tsx
**The issue** 
I was only able to repro on a Release version on a physical device, and you can’t console.log, and wasn't able to clearly figure out what series of operations caused the issue. 
- But my best guess is that it was some sort of race condition with requesting permissions in HomeScreen and getting the user’s coordinates with the locationManager in BottomTabsScreen. 
- It seemed to only reproduce after my change to fix bug #1808, which moved the locationManager code from RootNavigator to BottomTabsScreen. This would put its execution much closer to HomeScreen’s.
**The fix** 
The approach in this fix was to guarantee we will ask for permissions whenever we ask for the user’s last known location. I do this by moving the locationPermission logic from HomeScreen to BottomTabsScreen, …
> fix: allow zooming to user location on first map view 

- dev-client/src/components/FeatureFlagControl.tsx
- dev-client/src/config/featureFlags.ts
- dev-client/src/config/index.ts
- dev-client/src/screens/UserSettingsScreen/UserSettingsScreen.tsx
- Adds a feature flag for offline: `FF_offline`
- Allows a user in a non-production environment to toggle the feature flag. The user must restart the app for the new feature flag value to take effect. (This seemed the easiest thing to implement right now, but still allowing for user control.)
Implements #2100 
There should be no visible difference in a production environment, but looks like this in a non-prod environment:
> feat: Add feature flag to gate offline functionality

- dev-client/src/App.tsx
- dev-client/src/components/modals/PermissionsRequestWrapper.tsx
- dev-client/src/context/AppPermissionsContext.tsx
- dev-client/src/hooks/appPermissionsHooks.ts
- dev-client/src/screens/BottomTabsScreen.tsx
- dev-client/src/screens/HomeScreen/HomeScreen.tsx
- dev-client/src/screens/HomeScreen/components/MapSearch.tsx
**Issue**: Various issues with foreground permissions and zooming to the user's location on the map were caused by the expo-location library's `useForegroundPermissions` hook:
1. It only updates permissions on call to get(). 
2. When get() is called, the updated permissions are only local to component using the hook; it does not cause other components to re-render. This means components could be using outdated permissions. 
**Solution**: This PR makes and uses a hook that will update all components when foreground permissions are changed 
within the app (e.g., null to denied, or denied to granted), OR 
outside the app (in app settings there’s “Allow only while using the app”, “Ask every time”, and “Don’t allow”). 
**FYI** I do not recommend looking through the commits; it's chaos in there …
> fix: Changing location permissions should update components immediately

- dev-client/src/App.tsx
- dev-client/src/store/index.ts
- dev-client/src/store/persistence.test.ts
- dev-client/src/store/persistence.ts
Minimal implementation of redux state persistence! Currently the behavior is behind the offline feature flag.
This small amount of code is surprisingly effective. With just these changes, the app now goes to directly to the home screen and (if you comment out the hardwired `fetchSoilDataForUser` call) immediately displays all the user's data on launch:
[Launching straight to home screen](https://github.com/user-attachments/assets/b18167d6-283c-4de1-87fd-7ca0ebaed9e8)
Related to #1931 
Fixes #2164
> feat: redux state persistence

- dev-client/src/navigation/navigators/BottomNavigator.tsx
Previously, the user was able to hit 'back' on their device after logging out and access the application screens that are gated behind the login flow. Use a different navigation method when handling logout to prevent this from happening.
#1790 
1) Log in
2) Navigate to some screens
3) Log out
4) Press back
5) Observe that the app closes, rather than going back to previously-seen screens
> fix: use replace() rather than navigate() to avoid issues with back button

- dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
* add scroll view to transfer sites screen
* replace FlatList with map to avoid
```
ERROR  Warning: VirtualizedLists should never be nested inside plain ScrollViews with the same orientation because it can break windowing and other functionality - use another VirtualizedList-backed container instead.
```
Addresses #566.
> fix: add scroll view to transfer sites screen

- dev-client/src/components/ListFilter.tsx
- dev-client/src/screens/HomeScreen/components/SiteFilterModal.tsx
- dev-client/src/screens/ProjectListScreen/ProjectListScreen.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Allow projects to be sorted by date, not just name.
Addresses #690.
> fix: allow projects to be sorted by date

- dev-client/src/screens/ProjectTeamScreen/components/UserItem.tsx
This will affect the list of users for a project. The max width will now cause the text in the chip to wrap, instead of making the chip grow arbitrarily big. This is not a big issue currently, 
Add-on to #[#1877](https://github.com/techmatters/terraso-mobile-client/issues/1877)
With long chip text (increased system font size on right):
In Spanish with large font size:
This shows the maximum width a pill could be with this change (150px). Note that this is just for reference; in the actual behavior, pills will shrink to just fit the text:
> fix: Set maxWidth for chip in UserItem

- dev-client/app.config.ts
set LSMinimumSystemVersion to 12.0. fixes ITMS-90899 warning:
>ITMS-90899: Macs with Apple silicon support issue - The app isn‘t compatible with the provided minimum macOS version of 11.0. It can run on macOS 12.0 or later. Please specify an LSMinimumSystemVersion value of 12.0 or later in a new build, or select a compatible version in App Store Connect. For details, visit: https://developer.apple.com/help/app-store-connect/manage-your-apps-availability/manage-availability-of-iphone-and-ipad-apps-on-macs-with-apple-silicon.
> build: set LSMinimumSystemVersion to 12.0

- dev-client/src/App.tsx
- dev-client/src/config/index.ts
Add tracePropogationTargets to Sentry config. Should enable coordination with backend traces.
Documentation:
https://docs.sentry.io/platforms/react-native/tracing/instrumentation/automatic-instrumentation/
> fix: add tracePropogationTargets to Sentry config

- dev-client/src/App.tsx
enableCaptureFailedRequests for Sentry.
Allows us to capture failed HTTP requests.
> fix: enableCaptureFailedRequests for Sentry

- dev-client/__tests__/snapshot/SlopeScreen-test.tsx
- dev-client/src/App.tsx
- dev-client/src/components/buttons/SyncButton.tsx
- dev-client/src/model/soilId/soilIdSelectors.ts
- dev-client/src/model/soilId/soilIdSlice.ts
- dev-client/src/model/sync/sync.test.ts
- dev-client/src/model/sync/sync.ts
- dev-client/src/store/persistence.test.ts
- dev-client/src/store/persistence.ts
Add a data model to track changes relevant to the sync system. Entities have change records containing a revision ID and information about the last change and last successful sync. The Soil ID slice tracks changes for soil data by updating the change records when mutations occur and marking them as synced when user data is loaded from the server. The number of un-synced sites is exposed through the sync button component for diagnostic purposes.
Also adds a basic system for patching data loaded from disk during startup -- ultimately we will want this to work by merging the slices' default initial states with the states saved to mmkv, however circular app dependencies prevented this and so we should revisit it as follow-on work once the main offline feature is done.
Fixes #2278
Make changes …
> feat: soil change tracking

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/src/components/buttons/SyncButton.tsx
- dev-client/src/model/project/projectGlobalReducer.ts
- dev-client/src/model/project/projectSlice.ts
- dev-client/src/model/site/siteGlobalReducer.ts
- dev-client/src/model/site/siteSlice.ts
- dev-client/src/model/soilId/soilIdGlobalReducer.ts
- dev-client/src/model/soilId/soilIdSlice.ts
- dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectRoleScreen.tsx
- dev-client/src/screens/CreateProjectScreen/components/CreateProjectForm.tsx
- dev-client/src/screens/CreateSiteScreen/CreateSiteScreen.tsx
- dev-client/src/screens/EditProjectInstructionsScreen.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
- dev-client/src/screens/ProjectSettingsScreen.tsx
- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
- dev-client/src/screens/SitesScreen/SitesScreen.tsx
- dev-client/src/store/index.ts
- dev-client/src/store/reducers.ts
**Please review one commit at a time.** git really mangled the diff, so i rewrote the commit history and it's way cleaner/more comprehensible if you go one at a time and read the descriptions.
Ready for first round of review/discussion. Explanation (will crystallize into docs in the code once consensus is reached):
The only functional difference this PR introduces is that there are no longer actions which modify the state over the course of several dispatches. In order to make that functional change, I had to do a decent chunk of refactoring. I only want to merge this PR if there's consensus that the new shape of our redux code is an improvement on the old shape.
- creates a helper function `createGlobalReducer` which allows you to create a reducer which can act on the entire redux state …
> feat: global redux actions

- dev-client/src/components/buttons/icons/IconButton.tsx
Add support for the `disabled` property in `IconButton`. It prevents press interactions, is reflected in accessibility state, and has its own style.
#2365
Set the `disabled` property to `true` on an `IconButton` instance and verify the interaction and style are as expected.
> feat: add disabled state to IconButton

- dev-client/package-lock.json
- dev-client/package.json
update react-native-gesture-handler to 2.20.2.
> build: update react-native-gesture-handler to 2.20.2

- dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Rework soil cracks page helper text.
After:
Addresses https://github.com/techmatters/terraso-product/issues/976.
> fix: rework soil cracks page helper text

- dev-client/src/model/soilId/actions/remoteSoilDataActions.ts
- dev-client/src/model/soilId/actions/soilDataActionFields.ts
- dev-client/src/model/soilId/actions/soilDataDiff.test.ts
- dev-client/src/model/soilId/actions/soilDataDiff.ts
Enhance the basic `soilDataDiff` system introduced in #2279 to support tracking changes to all fields. The new methods plug into the `remoteSoilDataActions` methods for generating push input and populate the push input with the diff of the last-synced data from the server.
Note: this PR must be reviewed after https://github.com/techmatters/terraso-mobile-client/pull/2413, as it builds on that changeset.
#2283
Make changes to individual fields on soil data and verify that the server only receives push input for those fields / depth intervals etc.
> feat: sync diff

- dev-client/__tests__/snapshot/__snapshots__/SoilScreen-test.tsx.snap
- dev-client/src/screens/SoilScreen/components/SoilDepthSummary.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Correct strings for texture class/soil texture. Courtney and I went over the screens and text together. What's in the build is now correct (and supersedes any discrepencies in #2225 or Figma).
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2225.
> fix: correct strings for texture class/soil texture

- dev-client/src/components/buttons/TextButton.tsx
- dev-client/src/screens/SoilScreen/SoilScreen.tsx
Changes the `SoilScreen`'s depth interval preset modal trigger from an `IconButton` to `TextButton`.
Related to #2069
Button should no longer be icon button.
> feat: change site depth preset button from `IconButton` to `TextButton`

- dev-client/src/hooks/connectivityHooks.ts
- dev-client/src/screens/UserSettingsScreen/components/menu/DeleteAccountItem.tsx
- dev-client/src/screens/UserSettingsScreen/components/menu/SignOutItem.tsx
Disables the sign out and delete account buttons on the user settings screen when offline.
@knipec `useIsOffline` returns `boolean | null`, should it just return `boolean`? or is the intention for `null` to mean "unknown" and different components might want to handle that case differently?
Related to #2376 
Buttons should be disabled when offline.
> feat: disable user settings buttons when offline

- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/translations/en.json
- correct spelling of "those"
- use correct i18n key for site deletion confirmation strings
- change data -> observations for change soil pit depths dialog
Addresses #2472 #2469.
> fix: fix en.json string typo and incorrect key in tsx file

- dev-client/package-lock.json
- dev-client/package.json
Revert react-native-screens to 4.1.0.
Addresses #2510.
> build: revert react-native-screens to 4.1.0

- dev-client/src/components/tooltips/Tooltip.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteForm.tsx
- dev-client/src/theme.ts
Updates the `Tooltip` component to match the new design spec. Waiting on confirmation of a couple things in [this Figma thread](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN?node-id=7281-34294&m=dev#1032530124) before fully ready to merge.
Related to #1776 
Tooltip component should look like the design. I believe the only example right now is on the `?` on the create site screen.
> feat: tooltip component design updates

- dev-client/src/screens/SitesScreen/components/SiteListBottomSheet.tsx
Wrap EmptySiteMessage in BottomSheetScrollView
Thanks to @tm-ruxandra for the fix.
Addresses #2512.
> fix: wrap EmptySiteMessage in BottomSheetScrollView

- dev-client/src/screens/LocationScreens/components/soilInfo/SoilInfoDisplay.tsx
Simple fix, in draft because I am double checking something with courtney in [this figma thread](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN?node-id=9963-20562#1026908630)
Related to #2481
Should see subclass on soil info sheet.
> fix: display LCC subclass

- dev-client/locales/po/en.po
- dev-client/locales/po/es.po
- dev-client/src/screens/SitesScreen/components/TemporaryLocationCallout.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
On the temporary site popover, disable data fetching and site creation when offline.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2560
> fix: temporary site popover: disable when offline

- dev-client/__tests__/snapshot/__snapshots__/ProjectViewScreen-test.tsx.snap
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
Make public/private radio buttons horizontal instead of vertically stacked.
Addresses https://github.com/techmatters/terraso-mobile-client/issues/2568
> fix: make private/public radio blocks horizontal instead of vertical

- dev-client/locales/po/en.po
- dev-client/locales/po/es.po
- dev-client/src/App.tsx
- dev-client/src/components/NativeBaseAdapters.tsx
- dev-client/src/components/buttons/DismissButton.tsx
- dev-client/src/components/buttons/TextButton.tsx
- dev-client/src/components/dataRequirements/handleMissingData.ts
- dev-client/src/components/dialogs/ErrorDialog.tsx
- dev-client/src/components/links/ExternalLink.tsx
- dev-client/src/context/SyncNotificationContext.tsx
- dev-client/src/theme.ts
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Add a new dialog which implements the sync error notification requirements. The dialog is exposed to the application through a new "sync notification context", which the missing site pull handler now uses instead of the generic Android toast. This context can also be reused for handling push errors.
#2324 
Trigger a sync error condition (for example, navigate to a site and then delete that site). Trigger a pull and observe the error dialog.
> Feat: sync conflict notification

- dev-client/src/components/content/typography/DisableableText.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/SoilIdMatchSelector.tsx
Disable soil ID match selector when offline. Add a new `DisableableText` typography component to help implement this type of feature in the future.
#2516
Enter offline mode and navigate to a soil ID match for a site. Observe that the selection checkbox is still visible but it and its text appear disabled. Interacting with it does not change the user's selection.
> feat: disable soil id match selector when offline

- dev-client/__tests__/integration/store/sync/PushDispatcher.test.tsx
- dev-client/src/store/sync/PushDispatcher.tsx
(Depends on https://github.com/techmatters/terraso-mobile-client/pull/2572)
Show a sync error notification when a push completes with sync errors.
Fixes #2293
Push with an error condition (e.g., to a deleted site). Observe the error notification.
> feat: push error notification

- dev-client/src/components/dialogs/ErrorDialog.tsx
The error dialog was unintentionally checked in with its `isOpen` state set to `true` by default. Fix this oversight.
#2293
Open application and verify that dialog does not show initially.
> fix: error dialog should not be open by default

- dev-client/src/components/dialogs/ErrorDialog.tsx
- dev-client/src/context/SyncNotificationContext.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Use correct support url for sync conflict notifications. `ErrorDialog` clients can now pass in an optional custom URL which takes precedence over the main Terraso site.
#2324
Verify sync error dialog URL.
> fix: use correct support url for sync conflict notifications

- dev-client/src/navigation/screenDefinitions.tsx
- dev-client/src/screens/EditPinnedNoteScreen.tsx
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/LocationScreens/components/PinnedNoteButton.tsx
- dev-client/src/screens/ProjectInputScreen/ProjectInputScreen.tsx
- dev-client/src/screens/SiteNotesScreen/components/PinnedNoteCard.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Renames "project instructions" to "pinned note" in the code, to match what this is called in the app.
I did not changed Project.siteInstructions yet, as that requires a shared client update.
Partially addresses #2625.
> refactor: rename instructions to pinned note

- dev-client/src/screens/SitesScreen/components/CustomUserLocation.tsx
- dev-client/src/screens/SitesScreen/components/SiteMap.tsx
- I expect re-rendering when permissions change should allow the user to see the blue location marker on the map when they first use the app. 
- However, the issue only reproes on a physical Android device, and tbh I don't want to go through the hassle of making a tagged release just to test it for myself. I suspect this change is at least not bad, and I will test it in the next beta release unless someone thinks I shouldn't do this. 😅 
- Also, I think we shouldn't show the location marker when they have revoked location permissions. (Side note: The map will still zoom, as that's determined by the userLocation in redux, which does not get cleared when permissions are revoked).
- I think it's also not ideal that we don't just use the userLocation in redux to determine where to draw the …
> fix: Don't show user location dot when permissions aren't granted + re-render when permissions change.

- dev-client/src/context/SoilIdMatchContext.tsx
- dev-client/src/model/soilIdMatch/soilIdMatchSlice.ts
- dev-client/src/model/soilIdMatch/soilIdMatches.test.tsx
- dev-client/src/model/soilIdMatch/soilIdMatches.ts
Flush any data-based matches which have error statuses when the app first enters online mode.
[#1179](https://github.com/techmatters/terraso-product/issues/1179)
Simulate a soil ID error when loading data-based matches (a site at a coordinate with no soilweb data, for example). Restart the application and verify that it attempts to reload the data when the user views that site again.
> feat: offline soil id errors

- dev-client/src/hooks/useMapSuggestions.ts
- dev-client/src/screens/SitesScreen/SitesScreen.tsx
- dev-client/src/screens/SitesScreen/components/search/MapSearch.tsx
- dev-client/src/screens/SitesScreen/components/search/MapSearchOfflineAlertBox.tsx
- dev-client/src/screens/SitesScreen/components/search/MapSearchOfflineBox.tsx
- dev-client/src/screens/SitesScreen/components/search/MapSearchSuggestionBox.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Disable suggestion API calls when offline. Instead, display a message box styled similar to the Autocomplete component explaining to the user that only exact-coordinate matches are supported.
#2367
Use search bar while offline and verify that expected message box is visible in place of autocomplete suggestions.
> feat: offline map search

- dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap
- dev-client/src/components/SoilIdStatusDisplay.tsx
- dev-client/src/screens/LocationScreens/components/LocationSoilIdCard.tsx
- dev-client/src/screens/LocationScreens/components/soilId/SoilIdMatchesSection.tsx
- dev-client/src/screens/LocationScreens/components/soilInfo/PropertiesScoreDisplay.tsx
- dev-client/src/screens/SitesScreen/components/TemporaryLocationCallout.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Correct various offline Soil ID displays to reflect intended behavior for soil ID data that was loaded before going offline. Clean up some nearby offline behavior while we're there.
#2415
Confirm offline appearance for affected displays for sites that both do and do not have already-loaded soil ID data.
> fix: offline soil id displays

- dev-client/src/model/soilIdMatch/soilIdMatches.test.tsx
- dev-client/src/model/soilIdMatch/soilIdMatches.ts
Improve consistency of offline soil ID experience by caching location-based matches with the same precision used by UI coordinate rendering.
#2415
Select a point on the map while online, loading soil ID data, and note its coordinates. Go offline and search for the same coordinates. Verify that soil ID data is still displayed.
> fix: make soil id location cache use same precision as ui elements

- dev-client/src/components/ScreenFormWrapper.tsx
- dev-client/src/components/modals/ActionsModal.tsx
- dev-client/src/components/modals/ConfirmDeleteDepthModal.tsx
- dev-client/src/components/modals/ConfirmModal.tsx
- dev-client/src/components/modals/PermissionsRequestWrapper.tsx
- dev-client/src/components/modals/SignOutModal.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorAnalysisHomeScreen.tsx
- dev-client/src/screens/ManageTeamMemberScreen.tsx
- dev-client/src/screens/ProjectInputScreen/SoilPitSettings.tsx
- dev-client/src/screens/ProjectSettingsScreen.tsx
- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/screens/ProjectTeamScreen/components/UserItem.tsx
- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
- dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/ColorDisplay.tsx
- dev-client/src/screens/SoilScreen/ColorScreen/components/SwitchWorkflowButton.tsx
- dev-client/src/screens/SoilScreen/components/EditDepthModal.tsx
- dev-client/src/screens/SoilScreen/components/EditSiteSoilDepthPreset.tsx
Update `ActionsModal` button usages to replace old `ActionButton` with `DialogButton`. Along the way, update `SiteTransferProjectScreen` to use correct button styling.
#2709
Transfer sites to a project and verify confirm dialog styling. Verify other ActionsModal styles (for example, logging out or deleting a depth interval.)
> feat: actions modal buttons

- dev-client/src/screens/LocationScreens/components/PinnedNoteButton.tsx
Fix incorrect callback usage for `PinnedNoteButton`.
#1856
Verify that the pinned note button correctly navigates to the pinned note screen.
> fix: incorrect callback usage for pinned note button

- dev-client/src/screens/ManageTeamMemberScreen.tsx
Update Manage Team Member screen buttons to match new specification.
#2711
Go to manage team member screen. Verify placement of save button, and that it is only enabled when a change has been made.
> feat: button behavior updates for ManageTeamMember

- dev-client/src/screens/SiteTransferProjectScreen/SiteTransferProjectScreen.tsx
Fix the placement of the FAB on the transfer sites screen to correctly position itself relative to the screen's other content.
#1856
Verify FAB position with accordion open and closed, and for site list long enough to trigger scroll behavior.
> fix: correct placement of transfer sites screen FAB

- dev-client/src/screens/SitesScreen/components/search/MapSearchOfflineAlertBox.tsx
Fix color for offline map search alert box.
Fixes #2367
Search while offline and observe color of alert box.
> fix: don't use disabled color for offline search alert box.

- dev-client/src/screens/CreateProjectScreen/components/ProjectForm.tsx
Reset the `EditProjectForm` after a successful submit, to clear the dirty flag and correctly disable the submit button until more changes are made.
#2712
Edit a project, save changes, and verify enabled-ness of submit button.
> fix: reset dirty flag when submitting edit project form

- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/translations/en.json
- Change `cannot` to `can’t` in confirmation messages
- fix string key for delete site modal
Addresses #2472.
> fix: change `cannot` to `can’t` in confirmation messages; correct delete site modal key

- dev-client/src/screens/SoilScreen/components/SoilSurfaceScreen.tsx
Reorder soil cracking screen to match design
Addresses #2525.
> fix: reorder soil cracking screen to match design

- dev-client/src/screens/LocationScreens/components/soilInfo/SoilInfoDisplay.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
Display "Not available" when LCC is not available on the soil info screens.
Fixes, once QA'd, https://github.com/techmatters/soil-id-algorithm/issues/119
Soil info screen should now show "Not available" for LCC at certain coordinates (see issue for context).
> fix: display "Not available" when LCC is not available

- dev-client/src/model/soilIdMatch/actions/soilIdMatchActions.ts
- dev-client/src/model/soilIdMatch/soilIdMatches.test.tsx
- dev-client/src/model/soilIdMatch/soilIdMatches.ts
Changes the `fetchLocationBasedSoilMatches` redux action to secretly call the `fetchDataBasedSoilMatches` endpoint with an empty set of data. See discussion on https://github.com/techmatters/soil-id-algorithm/issues/126 for why this is desirable behaviorally. This is in draft because it puts the codebase in a kinda hacky state where the method names aren't really honest anymore, but I wanted to record my progress before I take time off.
Related to https://github.com/techmatters/soil-id-algorithm/issues/126. Depends on https://github.com/techmatters/terraso-client-shared/pull/1112.
There should be no difference in the soil ID results now before or after creating a site.
> feat: list/rank soil inconsistency workaround

- .github/workflows/auto-approve.yml
- .github/workflows/auto-merge.yml
- .github/workflows/dependencies-branch.yml
Sunday: Automatically merge dependabot PRs on depdendencies branch (if they pass tests). This will allow the merge queue to be auto-populated instead of requiring someone to click "add to queue" for each PR.
Monday: Create a PR for the dependencies branch into main (the merge queue should be empty at this point).
Saturday: Create a fresh dependencies branch.
> build: automatically merge dependabot PRs on dependencies branch (if they pass tests)

- dev-client/__tests__/integration/EditSiteNoteScreen.test.tsx
- dev-client/__tests__/integration/screens/SiteSettingsScreen.test.tsx
- dev-client/src/App.tsx
- dev-client/src/components/dataRequirements/handleMissingData.ts
- dev-client/src/screens/AddUserToProjectScreen/AddUserToProjectRoleScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorCropReferenceScreen.tsx
- dev-client/src/screens/ColorAnalysisScreen/ColorCropSoilScreen.tsx
- dev-client/src/screens/CreateSiteScreen/components/CreateSiteView.tsx
- dev-client/src/screens/SiteNotesScreen/EditSiteNoteScreen.tsx
- dev-client/src/screens/SiteSettingsScreen/SiteSettingsScreen.tsx
- dev-client/src/screens/WelcomeScreen.tsx
Use `popTo` instead of `navigate` in places where we want `navigate` to pop instead of push for screens which are already in the stack, since `navigate` no longer does that for us.
I still need to look into how to add tests for this.
Related to #2513 
Navigation flows should no longer have weird behavior for:
- create site
- adding user to a project
- color algorithm camera workflow
- deleting a site
- welcome screen
- viewing a screen which is deleted remotely
> fix: app navigation for react navigation v7

- .github/workflows/build-shared-ios.yml
Disables the iOS build cache, per/pending discussion in https://github.com/techmatters/terraso-product/issues/1211
Closes https://github.com/techmatters/terraso-product/issues/1211
> chore: disable ios build cache

- dev-client/src/screens/SitesScreen/SitesScreen.tsx
- dev-client/src/screens/SitesScreen/components/MapHeader.tsx
- dev-client/src/screens/SitesScreen/components/search/MapSearch.tsx
Reorganizes the map search code so that we are memoizing the autocomplete props properly. It'll be easier to review if you do it one commit at a time, as there's a fix commit followed by a refactor commit.
I struggled to write a test for this:
- i got the following error just from trying to render the component in a test:
```
Cannot load null or undefined font source: { "material-community":  }. 
Expected asset of type `FontSource` for fontFamily of name: "material-community"
```
- even if i can get the component to render, i'm not sure how to test focus state :thinking: 
Related to #2826 
Map search should be focusable again.
> fix: map search

- dev-client/src/components/SyncContent.tsx
So we don't show this dev-team-only stuff when we turn on the Offline feature flag:
N/A 
When the Offline feature flag is ON, but the Testing feature flag is OFF, make sure we don't see the sync content at the top of the app
> fix: Only show dev-only SyncContent if FF_testing flag is on

- dev-client/src/components/dataRequirements/handleMissingData.ts
- dev-client/src/screens/SlopeScreen/SlopeShapeScreen.tsx
- dev-client/src/screens/SlopeScreen/SlopeSteepnessScreen.tsx
- dev-client/src/store/selectors.ts
A few edge cases that slipped through the cracks! Addressing the problem more holistically with tests or more honest type annotations is out of scope for launch unfortunately, and is tracked by https://github.com/techmatters/terraso-mobile-client/issues/2854
Related to https://github.com/techmatters/terraso-mobile-client/issues/2290
Should no longer see blank screen when viewing a data input screen for a site which gets deleted remotely.
> fix: screen data requirement bugs

- .github/ISSUE_TEMPLATE/mobile_bug_report.yml
Please check to see that this does add the type "Bug" to the report.
Removes "bug" label from Bug Report Form and adds "bug" type to resulting issues. 
Fixes #....
> fix: use `bug` type for mobile bug reports

- dev-client/src/model/sync/records.test.ts
Fixes a typo in a test which causes it to flake non-deterministically. It seemed easier to just fix it than file an issue. The test now matches a similar test in a file. Here is an example of a failed run: https://github.com/techmatters/terraso-mobile-client/actions/runs/12896446677/attempts/1
Screenshot because the logs don't last forever:
Tests should still pass. There's no way to reliably trigger the flake so :shrug:
> fix: flakey test

- dev-client/src/persistence/kvStorage.test.ts
- dev-client/src/persistence/kvStorage.ts
I will take a bit to figure out if a test could've caught this, but I suspect there's no way to catch this in a test because the libraries' function gets mocked in tests.
Should fix the login crash #2860 
Can sign out.
> fix: change how we call some `mmkv` functions to avoid messing with javascript's `this`

- dev-client/__tests__/integration/models/soilId/soilIdMatchSelectors.test.ts
- dev-client/src/model/soilIdMatch/soilIdMatchSelectors.ts
- dev-client/src/store/selectors.ts
Yet another bug due to our house of cards of redux selector logic. Forgot to include the default soil data in a selector. This creates a bug specifically for newly created sites because when we pull, the backend supplies default soil data for all sites. So it's only when we've created a site but haven't pulled yet that we need to supply default data ourselves on the client. There's definitely a better way to architect this but it seems out of scope for this pre-launch fix, but I think I can write a localized test for it.
Not sure if there's a straightforward better way to architect this, I'm a bit scared of all the nested selectors :(
Related to #2858
Soil ID should now load for newly created sites.
> fix: properly load soil ID when creating new sites

- dev-client/src/components/FeatureFlagControl.tsx
- dev-client/src/screens/UserSettingsScreen/UserSettingsScreen.tsx
- Not urgent, but it was bugging me
- Move the feature flag control panel up and into a Scrollview so it doesn't get cut off on differently sized devices
- Follows the same pattern as the UI components section
Before:
After (on a different device, to be fair): 
Collapsed / Expanded
N/A
> fix: Reorganize the Feature Flag Control Panel

- .github/workflows/build-shared-ios.yml
update macos to 15 and xcode to 16.2
Should fix:
>ITMS-90725: SDK version issue - This app was built with the iOS 17.5 SDK. Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution.
> fix: update macos to 15 and xcode to 16.2

- .github/workflows/build-shared-ios.yml
The iOS build is broken on main. Will this fix it? Let's see... (Update: yes!)
Addresses #2940
Filed https://github.com/techmatters/terraso-mobile-client/issues/2943 to follow up in a couple months to see if we can change it back to using the latest Xcode version
If the build associated with this PR succeeds, that's a very positive sign
> fix: Fix the iOS build workflow xcode version to 16.2

- .github/workflows/build-shared-ios.yml
revert Xcode 16.2 hard-coding now that we can build cleanly with 16.3.
> fix: revert Xcode 16.2 hard-coding

- dev-client/.prettierignore
- dev-client/__tests__/integration/OfflineSnackbar.test.tsx
- dev-client/__tests__/integration/depthIntervalHelpers.test.ts
- dev-client/jest/integration/setup.ts
- dev-client/src/components/messages/OfflineSnackbar.tsx
Write tests for when the OfflineSnackbar component appears and disappears.
Also, allow files in `__tests__` and `__mocks__` to be affected by prettier
Thanks to @wseveraldojunior for the tips for getting this to work!
Addresses [#1233](https://github.com/techmatters/terraso-product/issues/1233)
> test: add some tests for offline snackbar

- dev-client/package.json
lint-staged command works in subdirectory
Based on https://github.com/lint-staged/lint-staged/issues/621#issuecomment-2683043450
> fix: lint-staged command works in subdirectory

- dev-client/package-lock.json
- dev-client/package.json
This reverts commit 7d233f32ffe365db9d4ace0109bbce3b49f577a1 and keeps the dependency on 10.1.33, because after bumping @rnmapbox/maps to 10.1.38, the app would crash on Android with
“Warning: TypeError: MapboxGLLocationManager.onLocationUpdate is not a function (it is undefined)”
I believe this is related to https://github.com/rnmapbox/maps/issues/3796 
Open app, make sure does not crash on Android or iOS
> Revert "build: update @rnmapbox/maps to 10.1.38 (#2959)"

- dev-client/package-lock.json
- dev-client/package.json
Alas! I thought it was ok to bump the uuid package version from 10 to 11, but it seems it causes the app to crash. So, sadly, taking client-shared back to a commit hash that uses uuid 10.0.0, and use uuid 10.0.0 in mobile-client as well.
Opening https://github.com/techmatters/terraso-mobile-client/issues/2968 to follow up on this.
A tangential follow-up to a change for https://github.com/techmatters/terraso-backend/issues/1618 
- App does not crash after login
- Tests pass
> fix: bump terraso-client-shared commit hash without bumping uuid version

- dev-client/package-lock.json
- dev-client/package.json
Follow-on to https://github.com/techmatters/terraso-mobile-client/pull/2966 because some @rnmapbox/maps version between 10.1.34 and 10.1.38 would cause a crash.
TODO: Do we need a task to try to update it in a couple months? Will dependabot do it automatically, or does fixing it to an exact version prevent dependabot from trying?
> fix: Remove the caret to precisely fix @rnmapbox/maps version

- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/SitesScreen/components/TemporaryLocationCallout.tsx
Don't display elevation on map popover or location dashboard, if unknown and outside the US
Addresses https://github.com/techmatters/terraso-product/issues/1308 
And should be undone with https://github.com/techmatters/terraso-mobile-client/issues/2664
[Here's a video of what it looks like now](https://tech-matters.slack.com/archives/C0376RCCXD2/p1751996709665269?thread_ts=1751996041.572489&cid=C0376RCCXD2)
> fix: Remove elevation if unknown and outside the US

- dev-client/locales/po/es.po
- dev-client/src/translations/es.json
Looks like the translation in POEditor accidentally got an extra `k`.
I edited the files in-place to fix it (didn't go through POEditor), but Derek also fixed this string in POEditor, so it should be fine for the future.
We don't expect this fix to make it into the 1.3 release, but it will go into the publicized release (1.3.1, I imagine)
> fix: correct spelling of Kastanozems in Spanish

- dev-client/src/model/soilIdMatch/actions/soilIdMatchInputs.ts
Looks like we just forgot to send along surfaceCracks in the SoilIdInput
Part of https://github.com/techmatters/terraso-product/issues/1279
Can now see it as part of the data sent to the backend with tcpdump
> fix: soil cracks should be included as soil id input

- Makefile
- dev-client/package.json
I found that running 
```
watchman watch-del-all
watchman shutdown-server
```
fixed a watchman error in my local environment, that `make clean-watchman` alone did not fix.
Because `npm run clean-watchman` already does the watch-del-all part, I only added the shutdown-server part.
Source: https://stackoverflow.com/questions/49443341/watchman-crawl-failed-retrying-once-with-node-crawler 
However, I'm not sure if/how this will affect watchman in other repos -- like if you have a backend, mobile-client, and web-client running at the same time and run this in mobile-client, I'm not sure if you'd need to do something extra to make backend and web-client continue to hot reload?
[[TODO: test that if reviewers aren't sure]]
> fix: Add watchman shutdown-server to clean-watchman

- dev-client/src/translations/en.json
Minor string update to make the text work for both temporary locations and sites
Based on comment https://github.com/techmatters/terraso-product/issues/1251#issuecomment-3145050099
> fix: Change soil id warning alert text to not reference 'site'

- README.md
In the README, removed outdated information on android signing and iOS CocoaPods.
Releases are handled by GitHub actions and CocoaPods by npm run prebuild.
> docs: remove outdated setup information in README

- dev-client/__tests__/snapshot/__snapshots__/SiteTabsScreen-test.tsx.snap
- dev-client/src/components/util/site.ts
- dev-client/src/model/elevation/elevationService.ts
- dev-client/src/screens/LocationScreens/LocationDashboardContent.tsx
- dev-client/src/screens/LocationScreens/components/LocationSoilIdCard.tsx
- dev-client/src/screens/SitesScreen/components/TemporaryLocationCallout.tsx
Use open-meteo elevation API instead of the nationalmap.gov API. This allows for global elevation data.
Fixes #2664.
Removes workaround from https://github.com/techmatters/terraso-mobile-client/pull/2991
> fix: get elevation for all locations, not just US locations

- dev-client/find-i18n-keys.mjs
- dev-client/package.json
- dev-client/scripts/localization/find-i18n-keys.mjs
- dev-client/src/components/content/info/privacy/DataPrivacyContent.tsx
- dev-client/src/screens/ProjectSitesScreen.tsx
- dev-client/src/screens/UserSettingsScreen/components/menu/PrivacyItem.tsx
- dev-client/src/screens/WelcomeScreen.tsx
- dev-client/src/translations/en.json
- dev-client/src/translations/es.json
also added command "npm run check-i18n" which will find most missing translation strings. this should probably run automatically at some point.
also moved a few strings into general section to avoid duplication (privacy_policy_link..., and terms_of_service_link...).
conformed the check script found the missing value and now all the values are good.
(it falsely reports projects.sites.sort., but not an actual problem).
> fix: repaired missing privacy_policy_label

- dev-client/src/translations/en.json
Update the error alert message string on the soil ID screen 
FYI: You can get an error via timeout of 20 seconds (as of [PR 3011](https://github.com/techmatters/terraso-mobile-client/pull/3011)), or if the soil ID algorithm crashes, or if there's a network error.
One of the changes to address https://github.com/techmatters/terraso-mobile-client/issues/2752
> fix: Update terminology for soil id error alert message

- .gitignore
Watchman sometimes creates cookie files that I think git should ignore: 
However, I'm not sure why it's creating the cookies in the dev-client directory. From the Watchman docs:
> The cookie is created in a directory that is expected not to go away. The obvious location is the root itself, but we'd like cookies not to show up in VCS operations. So if a VCS directory (.git, .hg or .svn) is found, that's where cookies are created instead.
> fix: make git ignore watchman cookie files

- dev-client/src/screens/WelcomeScreen.tsx
Welcome interstitial now looks like
Addresses #1305
> fix: remove a bullet point from the interstitial

- dev-client/app.config.ts
- dev-client/package-lock.json
- dev-client/package.json
The [iOS release build for v257beta failed ](https://github.com/techmatters/terraso-mobile-client/actions/runs/17772608093/job/50512353334#step:9:94) because the version had not yet been bumped from the last publicly approved version (1.3.1). So bump to 1.3.2.
> feat: bump client version to 1.3.2

- dev-client/package-lock.json
- dev-client/package.json
- dev-client/patches/expo-localization+16.0.1.patch
- dev-client/src/app/AppWrappers.tsx
- dev-client/src/app/PostHog.tsx
- Patch expo-localization so compatible with Xcode 26 which is stricter on switch statements without all cases
- Add identity to PostHog including email, name, and email_domain
- Add platform to PostHog for filtering out non 'production' platform
- [ Y  ] Corresponding issue has been opened
- [ N ] New tests added
- [ N/A ] English strings reviewed and copyedited
- [ N/A ] Strings are localized
- [ N/A ] Images are compressed (TinyPNG or svgo)
- [ N/A ] Sample environment file updated (when environment variables changed)
- [ Y ] Verified on mobile
- [ N/A ] Verified on desktop
- [ N/A ] Verified accessibility ([Accessibility - Web applications](https://docs.google.com/document/d/1VwPDyLqw7r_iISMgDZr1FdAmAqqOIIVIxQqsYA-HaHE/edit?usp=sharing))
This is the solution to issue 3046 (posthog …
> feat: posthog events with email
